In [197]:
import numpy as np
import pandas as pd

In [198]:
dict1 = {
    "name": ["kirti", "peter", "sam", "shubh"],
    "marks": [92, 93, 31, 86],
    "city": ["delhi", "calfornia", "goa", "chandigarh"]
}

In [199]:
df = pd.DataFrame(dict1)

In [200]:
print(df)

    name  marks        city
0  kirti     92       delhi
1  peter     93   calfornia
2    sam     31         goa
3  shubh     86  chandigarh

In [201]:
df.to_csv('data.csv')
df.to_csv('data_without_index.csv', index=False)

In [202]:
df.head(2)

    name  marks       city
0  kirti     92      delhi
1  peter     93  calfornia

In [203]:
df.tail(2)

    name  marks        city
2    sam     31         goa
3  shubh     86  chandigarh

In [204]:
df.describe()

           marks
count   4.000000
mean   75.500000
std    29.827281
min    31.000000
25%    72.250000
50%    89.000000
75%    92.250000
max    93.000000

In [205]:
trains = pd.read_csv('trains.csv')

In [206]:
trains

,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Train No.,speed,city
0,0,0,0,0,0,0,0,12238,50,delhi
1,1,1,1,1,1,1,1,38265,28,calfornia
2,2,2,2,2,2,2,2,98542,31,goa
3,3,3,3,3,3,3,3,17662,86,chandigarh

In [207]:
trains['speed'][0] = 50

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\3155761661.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  trains['speed'][0] = 50
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\3155761661.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trains['speed'][0] = 50

In [208]:
trains

,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Train No.,speed,city
0,0,0,0,0,0,0,0,12238,50,delhi
1,1,1,1,1,1,1,1,38265,28,calfornia
2,2,2,2,2,2,2,2,98542,31,goa
3,3,3,3,3,3,3,3,17662,86,chandigarh

In [209]:
trains.to_csv('trains.csv')

In [210]:
trains.index = ["first", "second", "third", " fourth"]
trains

,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Train No.,speed,city
first,0,0,0,0,0,0,0,12238,50,delhi
second,1,1,1,1,1,1,1,38265,28,calfornia
third,2,2,2,2,2,2,2,98542,31,goa
fourth,3,3,3,3,3,3,3,17662,86,chandigarh

In [211]:
ser = pd.Series(np.random.rand(34))
type(ser)
ser

0     0.755289
1     0.541052
2     0.704299
3     0.462053
4     0.440123
5     0.050390
6     0.972478
7     0.375211
8     0.484557
9     0.360354
10    0.812638
11    0.897345
12    0.482918
13    0.210947
14    0.321708
15    0.237117
16    0.677421
17    0.894750
18    0.963596
19    0.744659
20    0.885609
21    0.305723
22    0.198546
23    0.689517
24    0.260871
25    0.731497
26    0.997625
27    0.774922
28    0.503399
29    0.882813
30    0.129502
31    0.927065
32    0.162144
33    0.885312
dtype: float64

In [212]:
newdf = pd.DataFrame(np.random.rand(334, 5), index=np.arange(334))
print(type(newdf))
newdf

<class 'pandas.core.frame.DataFrame'>

            0         1         2         3         4
0    0.257194  0.604859  0.689354  0.863669  0.209202
1    0.026931  0.779018  0.758221  0.348112  0.118429
2    0.568654  0.804792  0.838724  0.513442  0.393518
3    0.883513  0.123531  0.669950  0.941568  0.656960
4    0.642737  0.203601  0.707837  0.347014  0.774811
..        ...       ...       ...       ...       ...
329  0.671171  0.909440  0.828858  0.963834  0.005679
330  0.636962  0.275939  0.604504  0.294882  0.281642
331  0.481532  0.644146  0.720217  0.441495  0.066500
332  0.804083  0.290125  0.852481  0.438535  0.475929
333  0.459420  0.013833  0.738270  0.008471  0.667356

[334 rows x 5 columns]

In [213]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.514682    0.493264    0.502247    0.489167    0.491199
std      0.293662    0.302010    0.290005    0.299626    0.300495
min      0.001198    0.002505    0.001322    0.002196    0.001022
25%      0.245903    0.239757    0.246252    0.236552    0.212498
50%      0.530235    0.471043    0.511144    0.472407    0.497932
75%      0.774340    0.769490    0.755537    0.753629    0.752589
max      0.999616    0.998413    0.999395    0.999578    0.997622

In [214]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [215]:
newdf[0][0] = "kirti"
newdf.head(2)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\2125280267.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0] = "kirti"
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\2125280267.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'kirti' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0] = "kirti"

          0         1         2         3         4
0     kirti  0.604859  0.689354  0.863669  0.209202
1  0.026931  0.779018  0.758221  0.348112  0.118429

In [216]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [217]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [218]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [219]:
newdf.to_numpy()

array([['kirti', 0.6048593655649919, 0.689353964788693,
        0.8636694103112929, 0.2092016907213512],
       [0.02693119007418343, 0.7790184568675882, 0.7582207813957726,
        0.34811205148679236, 0.11842948972251255],
       [0.5686540371725277, 0.8047920500348907, 0.8387241513326982,
        0.5134422638350329, 0.3935175346632531],
       ...,
       [0.4815320347140376, 0.6441460940456041, 0.7202165412799867,
        0.44149457733017394, 0.06649991427224611],
       [0.8040827046014508, 0.2901252980851097, 0.8524810613405416,
        0.43853541228866266, 0.4759288730853821],
       [0.4594202396883986, 0.01383329817536405, 0.7382699734864376,
        0.008470519795831688, 0.6673558957080273]],
      shape=(334, 5), dtype=object)

In [220]:
newdf[0][0]=0.728
newdf.head(2)

          0         1         2         3         4
0     0.728  0.604859  0.689354  0.863669  0.209202
1  0.026931  0.779018  0.758221  0.348112  0.118429

In [221]:
newdf.to_numpy()

array([[0.728, 0.6048593655649919, 0.689353964788693, 0.8636694103112929,
        0.2092016907213512],
       [0.02693119007418343, 0.7790184568675882, 0.7582207813957726,
        0.34811205148679236, 0.11842948972251255],
       [0.5686540371725277, 0.8047920500348907, 0.8387241513326982,
        0.5134422638350329, 0.3935175346632531],
       ...,
       [0.4815320347140376, 0.6441460940456041, 0.7202165412799867,
        0.44149457733017394, 0.06649991427224611],
       [0.8040827046014508, 0.2901252980851097, 0.8524810613405416,
        0.43853541228866266, 0.4759288730853821],
       [0.4594202396883986, 0.01383329817536405, 0.7382699734864376,
        0.008470519795831688, 0.6673558957080273]],
      shape=(334, 5), dtype=object)

In [222]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.728,0.026931,0.568654,0.883513,0.642737,0.830286,0.879574,0.812856,0.839823,0.723792,...,0.233848,0.612974,0.412818,0.625565,0.769023,0.671171,0.636962,0.481532,0.804083,0.45942
1,0.604859,0.779018,0.804792,0.123531,0.203601,0.616021,0.579737,0.952195,0.262473,0.73308,...,0.159789,0.914433,0.145454,0.755652,0.560665,0.90944,0.275939,0.644146,0.290125,0.013833
2,0.689354,0.758221,0.838724,0.66995,0.707837,0.270508,0.131929,0.466663,0.658268,0.061375,...,0.662198,0.59949,0.056703,0.025261,0.239653,0.828858,0.604504,0.720217,0.852481,0.73827
3,0.863669,0.348112,0.513442,0.941568,0.347014,0.137414,0.031108,0.696106,0.774209,0.771999,...,0.999449,0.132977,0.277732,0.233363,0.400471,0.963834,0.294882,0.441495,0.438535,0.008471
4,0.209202,0.118429,0.393518,0.65696,0.774811,0.79656,0.330346,0.130513,0.406143,0.67512,...,0.857869,0.552502,0.560445,0.671232,0.940616,0.005679,0.281642,0.0665,0.475929,0.667356

In [223]:
newdf.head()

          0         1         2         3         4
0     0.728  0.604859  0.689354  0.863669  0.209202
1  0.026931  0.779018  0.758221  0.348112  0.118429
2  0.568654  0.804792  0.838724  0.513442  0.393518
3  0.883513  0.123531  0.669950  0.941568  0.656960
4  0.642737  0.203601  0.707837  0.347014  0.774811

In [224]:
newdf.sort_index(axis = 1, ascending=False)
# across coloumns

            4         3         2         1         0
0    0.209202  0.863669  0.689354  0.604859     0.728
1    0.118429  0.348112  0.758221  0.779018  0.026931
2    0.393518  0.513442  0.838724  0.804792  0.568654
3    0.656960  0.941568  0.669950  0.123531  0.883513
4    0.774811  0.347014  0.707837  0.203601  0.642737
..        ...       ...       ...       ...       ...
329  0.005679  0.963834  0.828858  0.909440  0.671171
330  0.281642  0.294882  0.604504  0.275939  0.636962
331  0.066500  0.441495  0.720217  0.644146  0.481532
332  0.475929  0.438535  0.852481  0.290125  0.804083
333  0.667356  0.008471  0.738270  0.013833   0.45942

[334 rows x 5 columns]

In [225]:
newdf.sort_index(axis=0, ascending=False)
# across rows

            0         1         2         3         4
333   0.45942  0.013833  0.738270  0.008471  0.667356
332  0.804083  0.290125  0.852481  0.438535  0.475929
331  0.481532  0.644146  0.720217  0.441495  0.066500
330  0.636962  0.275939  0.604504  0.294882  0.281642
329  0.671171  0.909440  0.828858  0.963834  0.005679
..        ...       ...       ...       ...       ...
4    0.642737  0.203601  0.707837  0.347014  0.774811
3    0.883513  0.123531  0.669950  0.941568  0.656960
2    0.568654  0.804792  0.838724  0.513442  0.393518
1    0.026931  0.779018  0.758221  0.348112  0.118429
0       0.728  0.604859  0.689354  0.863669  0.209202

[334 rows x 5 columns]

In [226]:
type(newdf[0])

pandas.core.series.Series

In [227]:
newdf2 = newdf
# here newdf2 is the view (pointing to newdf)

In [228]:
newdf2[0][0] = 7283

In [229]:
newdf

            0         1         2         3         4
0        7283  0.604859  0.689354  0.863669  0.209202
1    0.026931  0.779018  0.758221  0.348112  0.118429
2    0.568654  0.804792  0.838724  0.513442  0.393518
3    0.883513  0.123531  0.669950  0.941568  0.656960
4    0.642737  0.203601  0.707837  0.347014  0.774811
..        ...       ...       ...       ...       ...
329  0.671171  0.909440  0.828858  0.963834  0.005679
330  0.636962  0.275939  0.604504  0.294882  0.281642
331  0.481532  0.644146  0.720217  0.441495  0.066500
332  0.804083  0.290125  0.852481  0.438535  0.475929
333   0.45942  0.013833  0.738270  0.008471  0.667356

[334 rows x 5 columns]

In [230]:
newdf3 = newdf.copy()
newdf3[0][0] = 82
newdf

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\575451395.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf3[0][0] = 82
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\575451395.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf3[0][0] = 82

            0         1         2         3         4
0        7283  0.604859  0.689354  0.863669  0.209202
1    0.026931  0.779018  0.758221  0.348112  0.118429
2    0.568654  0.804792  0.838724  0.513442  0.393518
3    0.883513  0.123531  0.669950  0.941568  0.656960
4    0.642737  0.203601  0.707837  0.347014  0.774811
..        ...       ...       ...       ...       ...
329  0.671171  0.909440  0.828858  0.963834  0.005679
330  0.636962  0.275939  0.604504  0.294882  0.281642
331  0.481532  0.644146  0.720217  0.441495  0.066500
332  0.804083  0.290125  0.852481  0.438535  0.475929
333   0.45942  0.013833  0.738270  0.008471  0.667356

[334 rows x 5 columns]

In [231]:
newdf

            0         1         2         3         4
0        7283  0.604859  0.689354  0.863669  0.209202
1    0.026931  0.779018  0.758221  0.348112  0.118429
2    0.568654  0.804792  0.838724  0.513442  0.393518
3    0.883513  0.123531  0.669950  0.941568  0.656960
4    0.642737  0.203601  0.707837  0.347014  0.774811
..        ...       ...       ...       ...       ...
329  0.671171  0.909440  0.828858  0.963834  0.005679
330  0.636962  0.275939  0.604504  0.294882  0.281642
331  0.481532  0.644146  0.720217  0.441495  0.066500
332  0.804083  0.290125  0.852481  0.438535  0.475929
333   0.45942  0.013833  0.738270  0.008471  0.667356

[334 rows x 5 columns]

In [232]:
newdf.loc[0,0] = 26
# helps in accessing the values by specifying the position

In [233]:
newdf

            0         1         2         3         4
0          26  0.604859  0.689354  0.863669  0.209202
1    0.026931  0.779018  0.758221  0.348112  0.118429
2    0.568654  0.804792  0.838724  0.513442  0.393518
3    0.883513  0.123531  0.669950  0.941568  0.656960
4    0.642737  0.203601  0.707837  0.347014  0.774811
..        ...       ...       ...       ...       ...
329  0.671171  0.909440  0.828858  0.963834  0.005679
330  0.636962  0.275939  0.604504  0.294882  0.281642
331  0.481532  0.644146  0.720217  0.441495  0.066500
332  0.804083  0.290125  0.852481  0.438535  0.475929
333   0.45942  0.013833  0.738270  0.008471  0.667356

[334 rows x 5 columns]

In [234]:
newdf.columns = list("ABCDE")

In [235]:
newdf

            A         B         C         D         E
0          26  0.604859  0.689354  0.863669  0.209202
1    0.026931  0.779018  0.758221  0.348112  0.118429
2    0.568654  0.804792  0.838724  0.513442  0.393518
3    0.883513  0.123531  0.669950  0.941568  0.656960
4    0.642737  0.203601  0.707837  0.347014  0.774811
..        ...       ...       ...       ...       ...
329  0.671171  0.909440  0.828858  0.963834  0.005679
330  0.636962  0.275939  0.604504  0.294882  0.281642
331  0.481532  0.644146  0.720217  0.441495  0.066500
332  0.804083  0.290125  0.852481  0.438535  0.475929
333   0.45942  0.013833  0.738270  0.008471  0.667356

[334 rows x 5 columns]

In [236]:
newdf = newdf.drop('A', axis=1)  
# changes column
newdf

            B         C         D         E
0    0.604859  0.689354  0.863669  0.209202
1    0.779018  0.758221  0.348112  0.118429
2    0.804792  0.838724  0.513442  0.393518
3    0.123531  0.669950  0.941568  0.656960
4    0.203601  0.707837  0.347014  0.774811
..        ...       ...       ...       ...
329  0.909440  0.828858  0.963834  0.005679
330  0.275939  0.604504  0.294882  0.281642
331  0.644146  0.720217  0.441495  0.066500
332  0.290125  0.852481  0.438535  0.475929
333  0.013833  0.738270  0.008471  0.667356

[334 rows x 4 columns]

In [237]:
newdf.loc[[1,2], ['C','D']]

          C         D
1  0.758221  0.348112
2  0.838724  0.513442

In [238]:
newdf.head()

          B         C         D         E
0  0.604859  0.689354  0.863669  0.209202
1  0.779018  0.758221  0.348112  0.118429
2  0.804792  0.838724  0.513442  0.393518
3  0.123531  0.669950  0.941568  0.656960
4  0.203601  0.707837  0.347014  0.774811

In [239]:
newdf.loc[[1,2],:]

          B         C         D         E
1  0.779018  0.758221  0.348112  0.118429
2  0.804792  0.838724  0.513442  0.393518

In [240]:
newdf.loc[(newdf['B']<0.3)]

            B         C         D         E
3    0.123531  0.669950  0.941568  0.656960
4    0.203601  0.707837  0.347014  0.774811
8    0.262473  0.658268  0.774209  0.406143
11   0.294695  0.563397  0.754146  0.891052
16   0.228146  0.576964  0.131159  0.506651
..        ...       ...       ...       ...
324  0.159789  0.662198  0.999449  0.857869
326  0.145454  0.056703  0.277732  0.560445
330  0.275939  0.604504  0.294882  0.281642
332  0.290125  0.852481  0.438535  0.475929
333  0.013833  0.738270  0.008471  0.667356

[105 rows x 4 columns]

In [241]:
newdf.loc[(newdf['B']<0.3) & (newdf['C']>0.1)]

            B         C         D         E
3    0.123531  0.669950  0.941568  0.656960
4    0.203601  0.707837  0.347014  0.774811
8    0.262473  0.658268  0.774209  0.406143
11   0.294695  0.563397  0.754146  0.891052
16   0.228146  0.576964  0.131159  0.506651
..        ...       ...       ...       ...
323  0.156730  0.462741  0.860619  0.205263
324  0.159789  0.662198  0.999449  0.857869
330  0.275939  0.604504  0.294882  0.281642
332  0.290125  0.852481  0.438535  0.475929
333  0.013833  0.738270  0.008471  0.667356

[93 rows x 4 columns]

In [242]:
newdf.head(8)

          B         C         D         E
0  0.604859  0.689354  0.863669  0.209202
1  0.779018  0.758221  0.348112  0.118429
2  0.804792  0.838724  0.513442  0.393518
3  0.123531  0.669950  0.941568  0.656960
4  0.203601  0.707837  0.347014  0.774811
5  0.616021  0.270508  0.137414  0.796560
6  0.579737  0.131929  0.031108  0.330346
7  0.952195  0.466663  0.696106  0.130513

In [243]:
newdf.iloc[0,3]
# access the value at 0 row, and skips 3 column -> value(0,E)

np.float64(0.2092016907213512)

In [244]:
newdf.iloc[[1,2], [1,2]]

          C         D
1  0.758221  0.348112
2  0.838724  0.513442

In [245]:
newdf.head(3)

          B         C         D         E
0  0.604859  0.689354  0.863669  0.209202
1  0.779018  0.758221  0.348112  0.118429
2  0.804792  0.838724  0.513442  0.393518

In [247]:
# {newdf = newdf.drop('E', axis=1) \n newdf} ==== {newdf.drop('E', axis=1, inplace = True)}

In [248]:
newdf.drop('E', axis=1, inplace = True)

In [249]:
newdf

            B         C         D
0    0.604859  0.689354  0.863669
1    0.779018  0.758221  0.348112
2    0.804792  0.838724  0.513442
3    0.123531  0.669950  0.941568
4    0.203601  0.707837  0.347014
..        ...       ...       ...
329  0.909440  0.828858  0.963834
330  0.275939  0.604504  0.294882
331  0.644146  0.720217  0.441495
332  0.290125  0.852481  0.438535
333  0.013833  0.738270  0.008471

[334 rows x 3 columns]