In [40]:
import numpy as np
import pandas as pd

In [41]:
dict1 = {
    "name": ["kirti", "peter", "sam", "shubh"],
    "marks": [92, 93, 31, 86],
    "city": ["delhi", "calfornia", "goa", "chandigarh"]
}

In [42]:
df = pd.DataFrame(dict1)

In [43]:
print(df)

    name  marks        city
0  kirti     92       delhi
1  peter     93   calfornia
2    sam     31         goa
3  shubh     86  chandigarh

In [44]:
df.to_csv('data.csv')
df.to_csv('data_without_index.csv', index=False)

In [45]:
df.head(2)

    name  marks       city
0  kirti     92      delhi
1  peter     93  calfornia

In [46]:
df.tail(2)

    name  marks        city
2    sam     31         goa
3  shubh     86  chandigarh

In [47]:
df.describe()

           marks
count   4.000000
mean   75.500000
std    29.827281
min    31.000000
25%    72.250000
50%    89.000000
75%    92.250000
max    93.000000

In [48]:
trains = pd.read_csv('trains.csv')

In [49]:
trains

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Train No.,speed,city
0,0,0,0,0,12238,50,delhi
1,1,1,1,1,38265,28,calfornia
2,2,2,2,2,98542,31,goa
3,3,3,3,3,17662,86,chandigarh

In [50]:
trains['speed'][0] = 50

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\3155761661.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  trains['speed'][0] = 50
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\3155761661.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trains['speed'][0] = 50

In [51]:
trains

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Train No.,speed,city
0,0,0,0,0,12238,50,delhi
1,1,1,1,1,38265,28,calfornia
2,2,2,2,2,98542,31,goa
3,3,3,3,3,17662,86,chandigarh

In [52]:
trains.to_csv('trains.csv')

In [53]:
trains.index = ["first", "second", "third", " fourth"]
trains

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Train No.,speed,city
first,0,0,0,0,12238,50,delhi
second,1,1,1,1,38265,28,calfornia
third,2,2,2,2,98542,31,goa
fourth,3,3,3,3,17662,86,chandigarh

In [54]:
ser = pd.Series(np.random.rand(34))
type(ser)
ser

0     0.530710
1     0.324125
2     0.217251
3     0.773699
4     0.052241
5     0.481298
6     0.072415
7     0.126286
8     0.817379
9     0.078679
10    0.970851
11    0.595360
12    0.515135
13    0.502202
14    0.070738
15    0.140719
16    0.236713
17    0.856693
18    0.549598
19    0.044256
20    0.684448
21    0.730338
22    0.386594
23    0.003227
24    0.042033
25    0.391030
26    0.712387
27    0.101642
28    0.005557
29    0.943981
30    0.493019
31    0.731570
32    0.540186
33    0.379656
dtype: float64

In [55]:
newdf = pd.DataFrame(np.random.rand(334, 5), index=np.arange(334))
print(type(newdf))
newdf

<class 'pandas.core.frame.DataFrame'>

            0         1         2         3         4
0    0.072351  0.466820  0.739729  0.259963  0.007056
1    0.112175  0.616717  0.247712  0.342971  0.667744
2    0.768326  0.982788  0.035965  0.778982  0.687182
3    0.310575  0.013628  0.467369  0.102780  0.795721
4    0.240806  0.570071  0.468235  0.000855  0.156248
..        ...       ...       ...       ...       ...
329  0.376647  0.117224  0.134571  0.537597  0.538992
330  0.445332  0.758475  0.663289  0.760203  0.495118
331  0.934482  0.180365  0.915065  0.791830  0.809531
332  0.727479  0.888386  0.443830  0.857717  0.933074
333  0.926092  0.382516  0.771528  0.436978  0.917342

[334 rows x 5 columns]

In [56]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.511219    0.491210    0.488791    0.498065    0.483436
std      0.299635    0.286146    0.299438    0.300974    0.287556
min      0.000403    0.001508    0.009019    0.000855    0.000143
25%      0.238529    0.258673    0.214216    0.248989    0.247812
50%      0.517437    0.487280    0.484816    0.495023    0.441077
75%      0.770172    0.734456    0.738518    0.776032    0.753212
max      0.997971    0.995967    0.997804    0.999116    0.994074

In [57]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [58]:
newdf[0][0] = "kirti"
newdf.head(2)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\2125280267.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0] = "kirti"
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\2125280267.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'kirti' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0] = "kirti"

          0         1         2         3         4
0     kirti  0.466820  0.739729  0.259963  0.007056
1  0.112175  0.616717  0.247712  0.342971  0.667744

In [59]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [60]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [61]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [62]:
newdf.to_numpy()

array([['kirti', 0.46682041381784956, 0.7397293553425534,
        0.2599631611172999, 0.007055533860635843],
       [0.11217539888687644, 0.616716799414746, 0.24771177213359097,
        0.3429705467258395, 0.6677440587412843],
       [0.7683263959932747, 0.9827876789462535, 0.03596498494628786,
        0.7789818065679206, 0.6871815911370722],
       ...,
       [0.934482179345386, 0.18036484927437435, 0.9150646033519092,
        0.7918299624329959, 0.8095310124546459],
       [0.7274788957632063, 0.8883864364689874, 0.44383004273711524,
        0.8577170107788348, 0.9330737999260664],
       [0.9260919444147965, 0.38251580581958133, 0.7715276361774737,
        0.436978277267966, 0.9173419438145748]],
      shape=(334, 5), dtype=object)

In [63]:
newdf[0][0]=0.728
newdf.head(2)

          0         1         2         3         4
0     0.728  0.466820  0.739729  0.259963  0.007056
1  0.112175  0.616717  0.247712  0.342971  0.667744

In [64]:
newdf.to_numpy()

array([[0.728, 0.46682041381784956, 0.7397293553425534,
        0.2599631611172999, 0.007055533860635843],
       [0.11217539888687644, 0.616716799414746, 0.24771177213359097,
        0.3429705467258395, 0.6677440587412843],
       [0.7683263959932747, 0.9827876789462535, 0.03596498494628786,
        0.7789818065679206, 0.6871815911370722],
       ...,
       [0.934482179345386, 0.18036484927437435, 0.9150646033519092,
        0.7918299624329959, 0.8095310124546459],
       [0.7274788957632063, 0.8883864364689874, 0.44383004273711524,
        0.8577170107788348, 0.9330737999260664],
       [0.9260919444147965, 0.38251580581958133, 0.7715276361774737,
        0.436978277267966, 0.9173419438145748]],
      shape=(334, 5), dtype=object)

In [65]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.728,0.112175,0.768326,0.310575,0.240806,0.696018,0.30536,0.532951,0.264009,0.760412,...,0.474405,0.674864,0.161043,0.18124,0.106072,0.376647,0.445332,0.934482,0.727479,0.926092
1,0.46682,0.616717,0.982788,0.013628,0.570071,0.853463,0.032377,0.268088,0.133137,0.043734,...,0.118975,0.962367,0.129061,0.402452,0.832022,0.117224,0.758475,0.180365,0.888386,0.382516
2,0.739729,0.247712,0.035965,0.467369,0.468235,0.794497,0.871567,0.44668,0.974893,0.035139,...,0.704669,0.23637,0.054567,0.827939,0.472031,0.134571,0.663289,0.915065,0.44383,0.771528
3,0.259963,0.342971,0.778982,0.10278,0.000855,0.012964,0.069807,0.078964,0.739677,0.942943,...,0.876169,0.790142,0.568371,0.109598,0.951797,0.537597,0.760203,0.79183,0.857717,0.436978
4,0.007056,0.667744,0.687182,0.795721,0.156248,0.753164,0.597981,0.250115,0.884267,0.073316,...,0.38112,0.565804,0.952134,0.26689,0.142001,0.538992,0.495118,0.809531,0.933074,0.917342

In [66]:
newdf.head()

          0         1         2         3         4
0     0.728  0.466820  0.739729  0.259963  0.007056
1  0.112175  0.616717  0.247712  0.342971  0.667744
2  0.768326  0.982788  0.035965  0.778982  0.687182
3  0.310575  0.013628  0.467369  0.102780  0.795721
4  0.240806  0.570071  0.468235  0.000855  0.156248

In [67]:
newdf.sort_index(axis = 1, ascending=False)
# across coloumns

            4         3         2         1         0
0    0.007056  0.259963  0.739729  0.466820     0.728
1    0.667744  0.342971  0.247712  0.616717  0.112175
2    0.687182  0.778982  0.035965  0.982788  0.768326
3    0.795721  0.102780  0.467369  0.013628  0.310575
4    0.156248  0.000855  0.468235  0.570071  0.240806
..        ...       ...       ...       ...       ...
329  0.538992  0.537597  0.134571  0.117224  0.376647
330  0.495118  0.760203  0.663289  0.758475  0.445332
331  0.809531  0.791830  0.915065  0.180365  0.934482
332  0.933074  0.857717  0.443830  0.888386  0.727479
333  0.917342  0.436978  0.771528  0.382516  0.926092

[334 rows x 5 columns]

In [68]:
newdf.sort_index(axis=0, ascending=False)
# across rows

            0         1         2         3         4
333  0.926092  0.382516  0.771528  0.436978  0.917342
332  0.727479  0.888386  0.443830  0.857717  0.933074
331  0.934482  0.180365  0.915065  0.791830  0.809531
330  0.445332  0.758475  0.663289  0.760203  0.495118
329  0.376647  0.117224  0.134571  0.537597  0.538992
..        ...       ...       ...       ...       ...
4    0.240806  0.570071  0.468235  0.000855  0.156248
3    0.310575  0.013628  0.467369  0.102780  0.795721
2    0.768326  0.982788  0.035965  0.778982  0.687182
1    0.112175  0.616717  0.247712  0.342971  0.667744
0       0.728  0.466820  0.739729  0.259963  0.007056

[334 rows x 5 columns]

In [69]:
type(newdf[0])

pandas.core.series.Series

In [70]:
newdf2 = newdf
# here newdf2 is the view (pointing to newdf)

In [71]:
newdf2[0][0] = 7283

In [72]:
newdf

            0         1         2         3         4
0        7283  0.466820  0.739729  0.259963  0.007056
1    0.112175  0.616717  0.247712  0.342971  0.667744
2    0.768326  0.982788  0.035965  0.778982  0.687182
3    0.310575  0.013628  0.467369  0.102780  0.795721
4    0.240806  0.570071  0.468235  0.000855  0.156248
..        ...       ...       ...       ...       ...
329  0.376647  0.117224  0.134571  0.537597  0.538992
330  0.445332  0.758475  0.663289  0.760203  0.495118
331  0.934482  0.180365  0.915065  0.791830  0.809531
332  0.727479  0.888386  0.443830  0.857717  0.933074
333  0.926092  0.382516  0.771528  0.436978  0.917342

[334 rows x 5 columns]

In [73]:
newdf3 = newdf.copy()
newdf3[0][0] = 82
newdf

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\575451395.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf3[0][0] = 82
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\575451395.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf3[0][0] = 82

            0         1         2         3         4
0        7283  0.466820  0.739729  0.259963  0.007056
1    0.112175  0.616717  0.247712  0.342971  0.667744
2    0.768326  0.982788  0.035965  0.778982  0.687182
3    0.310575  0.013628  0.467369  0.102780  0.795721
4    0.240806  0.570071  0.468235  0.000855  0.156248
..        ...       ...       ...       ...       ...
329  0.376647  0.117224  0.134571  0.537597  0.538992
330  0.445332  0.758475  0.663289  0.760203  0.495118
331  0.934482  0.180365  0.915065  0.791830  0.809531
332  0.727479  0.888386  0.443830  0.857717  0.933074
333  0.926092  0.382516  0.771528  0.436978  0.917342

[334 rows x 5 columns]

In [74]:
newdf

            0         1         2         3         4
0        7283  0.466820  0.739729  0.259963  0.007056
1    0.112175  0.616717  0.247712  0.342971  0.667744
2    0.768326  0.982788  0.035965  0.778982  0.687182
3    0.310575  0.013628  0.467369  0.102780  0.795721
4    0.240806  0.570071  0.468235  0.000855  0.156248
..        ...       ...       ...       ...       ...
329  0.376647  0.117224  0.134571  0.537597  0.538992
330  0.445332  0.758475  0.663289  0.760203  0.495118
331  0.934482  0.180365  0.915065  0.791830  0.809531
332  0.727479  0.888386  0.443830  0.857717  0.933074
333  0.926092  0.382516  0.771528  0.436978  0.917342

[334 rows x 5 columns]

In [78]:
newdf.loc[0,0] = 26

In [79]:
newdf

            0         1         2         3         4
0          26  0.466820  0.739729  0.259963  0.007056
1    0.112175  0.616717  0.247712  0.342971  0.667744
2    0.768326  0.982788  0.035965  0.778982  0.687182
3    0.310575  0.013628  0.467369  0.102780  0.795721
4    0.240806  0.570071  0.468235  0.000855  0.156248
..        ...       ...       ...       ...       ...
329  0.376647  0.117224  0.134571  0.537597  0.538992
330  0.445332  0.758475  0.663289  0.760203  0.495118
331  0.934482  0.180365  0.915065  0.791830  0.809531
332  0.727479  0.888386  0.443830  0.857717  0.933074
333  0.926092  0.382516  0.771528  0.436978  0.917342

[334 rows x 5 columns]

In [81]:
newdf.columns = list("ABCDE")

In [82]:
newdf

            A         B         C         D         E
0          26  0.466820  0.739729  0.259963  0.007056
1    0.112175  0.616717  0.247712  0.342971  0.667744
2    0.768326  0.982788  0.035965  0.778982  0.687182
3    0.310575  0.013628  0.467369  0.102780  0.795721
4    0.240806  0.570071  0.468235  0.000855  0.156248
..        ...       ...       ...       ...       ...
329  0.376647  0.117224  0.134571  0.537597  0.538992
330  0.445332  0.758475  0.663289  0.760203  0.495118
331  0.934482  0.180365  0.915065  0.791830  0.809531
332  0.727479  0.888386  0.443830  0.857717  0.933074
333  0.926092  0.382516  0.771528  0.436978  0.917342

[334 rows x 5 columns]

In [ ]:
newdf = newdf.drop('A', axis=1)
newdf

NameError: name 'A' is not defined