In [133]:
import numpy as np
import pandas as pd

In [134]:
dict1 = {
    "name": ["kirti", "peter", "sam", "shubh"],
    "marks": [92, 93, 31, 86],
    "city": ["delhi", "calfornia", "goa", "chandigarh"]
}

In [135]:
df = pd.DataFrame(dict1)

In [136]:
print(df)

    name  marks        city
0  kirti     92       delhi
1  peter     93   calfornia
2    sam     31         goa
3  shubh     86  chandigarh

In [137]:
df.to_csv('data.csv')
df.to_csv('data_without_index.csv', index=False)

In [138]:
df.head(2)

    name  marks       city
0  kirti     92      delhi
1  peter     93  calfornia

In [139]:
df.tail(2)

    name  marks        city
2    sam     31         goa
3  shubh     86  chandigarh

In [140]:
df.describe()

           marks
count   4.000000
mean   75.500000
std    29.827281
min    31.000000
25%    72.250000
50%    89.000000
75%    92.250000
max    93.000000

In [141]:
trains = pd.read_csv('trains.csv')

In [142]:
trains

,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Train No.,speed,city
0,0,0,0,0,0,0,12238,50,delhi
1,1,1,1,1,1,1,38265,28,calfornia
2,2,2,2,2,2,2,98542,31,goa
3,3,3,3,3,3,3,17662,86,chandigarh

In [143]:
trains['speed'][0] = 50

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\3155761661.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  trains['speed'][0] = 50
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\3155761661.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trains['speed'][0] = 50

In [144]:
trains

,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Train No.,speed,city
0,0,0,0,0,0,0,12238,50,delhi
1,1,1,1,1,1,1,38265,28,calfornia
2,2,2,2,2,2,2,98542,31,goa
3,3,3,3,3,3,3,17662,86,chandigarh

In [145]:
trains.to_csv('trains.csv')

In [146]:
trains.index = ["first", "second", "third", " fourth"]
trains

,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Train No.,speed,city
first,0,0,0,0,0,0,12238,50,delhi
second,1,1,1,1,1,1,38265,28,calfornia
third,2,2,2,2,2,2,98542,31,goa
fourth,3,3,3,3,3,3,17662,86,chandigarh

In [147]:
ser = pd.Series(np.random.rand(34))
type(ser)
ser

0     0.116440
1     0.571930
2     0.033667
3     0.699195
4     0.680661
5     0.996643
6     0.787625
7     0.889480
8     0.460773
9     0.678125
10    0.488876
11    0.097876
12    0.334531
13    0.383637
14    0.564606
15    0.868064
16    0.224230
17    0.264087
18    0.232118
19    0.300005
20    0.418027
21    0.466936
22    0.288208
23    0.795830
24    0.657368
25    0.760834
26    0.271297
27    0.105540
28    0.814697
29    0.830997
30    0.687279
31    0.279541
32    0.920646
33    0.917322
dtype: float64

In [148]:
newdf = pd.DataFrame(np.random.rand(334, 5), index=np.arange(334))
print(type(newdf))
newdf

<class 'pandas.core.frame.DataFrame'>

            0         1         2         3         4
0    0.045851  0.205121  0.523924  0.700803  0.879883
1    0.220325  0.467700  0.358358  0.131469  0.988455
2    0.177322  0.472727  0.814943  0.163342  0.074826
3    0.532886  0.085368  0.272566  0.217000  0.873583
4    0.673413  0.189538  0.567778  0.980649  0.916849
..        ...       ...       ...       ...       ...
329  0.444313  0.040191  0.388197  0.781128  0.196818
330  0.634070  0.063917  0.818672  0.984123  0.386153
331  0.294954  0.129844  0.346433  0.227695  0.044200
332  0.452859  0.357340  0.387504  0.047619  0.435259
333  0.076535  0.122899  0.538841  0.690804  0.951393

[334 rows x 5 columns]

In [149]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.508374    0.501607    0.523047    0.496091    0.507293
std      0.281791    0.293508    0.283032    0.286784    0.286661
min      0.000356    0.002113    0.003514    0.006513    0.001004
25%      0.274963    0.250130    0.307412    0.255955    0.270478
50%      0.534774    0.520463    0.515996    0.505810    0.516730
75%      0.753927    0.751514    0.756674    0.751417    0.742659
max      0.997479    0.997099    0.999965    0.999597    0.998810

In [150]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [151]:
newdf[0][0] = "kirti"
newdf.head(2)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\2125280267.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0] = "kirti"
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\2125280267.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'kirti' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0] = "kirti"

          0         1         2         3         4
0     kirti  0.205121  0.523924  0.700803  0.879883
1  0.220325  0.467700  0.358358  0.131469  0.988455

In [152]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [153]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [154]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [155]:
newdf.to_numpy()

array([['kirti', 0.20512053391510732, 0.5239244602296459,
        0.7008026130994396, 0.8798834389136504],
       [0.22032533323610126, 0.4676997155260263, 0.35835766379972667,
        0.13146916851195023, 0.9884550182906994],
       [0.1773222116270018, 0.4727267460648449, 0.8149432641171558,
        0.16334199164156038, 0.074826265664244],
       ...,
       [0.29495424312406926, 0.129844402562587, 0.34643335638560124,
        0.22769520122103148, 0.04420002436178594],
       [0.45285935069526395, 0.35733971039217816, 0.38750360597078837,
        0.04761935213891866, 0.435259319699567],
       [0.07653493856188243, 0.12289890959227101, 0.538840554388146,
        0.6908043996782903, 0.951393154915677]],
      shape=(334, 5), dtype=object)

In [156]:
newdf[0][0]=0.728
newdf.head(2)

          0         1         2         3         4
0     0.728  0.205121  0.523924  0.700803  0.879883
1  0.220325  0.467700  0.358358  0.131469  0.988455

In [157]:
newdf.to_numpy()

array([[0.728, 0.20512053391510732, 0.5239244602296459,
        0.7008026130994396, 0.8798834389136504],
       [0.22032533323610126, 0.4676997155260263, 0.35835766379972667,
        0.13146916851195023, 0.9884550182906994],
       [0.1773222116270018, 0.4727267460648449, 0.8149432641171558,
        0.16334199164156038, 0.074826265664244],
       ...,
       [0.29495424312406926, 0.129844402562587, 0.34643335638560124,
        0.22769520122103148, 0.04420002436178594],
       [0.45285935069526395, 0.35733971039217816, 0.38750360597078837,
        0.04761935213891866, 0.435259319699567],
       [0.07653493856188243, 0.12289890959227101, 0.538840554388146,
        0.6908043996782903, 0.951393154915677]],
      shape=(334, 5), dtype=object)

In [158]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.728,0.220325,0.177322,0.532886,0.673413,0.023765,0.38017,0.895709,0.517122,0.176616,...,0.208336,0.793812,0.931743,0.146093,0.892651,0.444313,0.63407,0.294954,0.452859,0.076535
1,0.205121,0.4677,0.472727,0.085368,0.189538,0.513716,0.42622,0.390747,0.868159,0.341967,...,0.585832,0.826845,0.01351,0.673346,0.963362,0.040191,0.063917,0.129844,0.35734,0.122899
2,0.523924,0.358358,0.814943,0.272566,0.567778,0.483145,0.109596,0.625624,0.979248,0.928573,...,0.231822,0.267993,0.371377,0.937298,0.670673,0.388197,0.818672,0.346433,0.387504,0.538841
3,0.700803,0.131469,0.163342,0.217,0.980649,0.611929,0.607392,0.903071,0.360683,0.351367,...,0.600874,0.450263,0.209204,0.71881,0.049058,0.781128,0.984123,0.227695,0.047619,0.690804
4,0.879883,0.988455,0.074826,0.873583,0.916849,0.664007,0.850605,0.332513,0.86247,0.860131,...,0.30992,0.698922,0.390393,0.699225,0.334373,0.196818,0.386153,0.0442,0.435259,0.951393

In [159]:
newdf.head()

          0         1         2         3         4
0     0.728  0.205121  0.523924  0.700803  0.879883
1  0.220325  0.467700  0.358358  0.131469  0.988455
2  0.177322  0.472727  0.814943  0.163342  0.074826
3  0.532886  0.085368  0.272566  0.217000  0.873583
4  0.673413  0.189538  0.567778  0.980649  0.916849

In [160]:
newdf.sort_index(axis = 1, ascending=False)
# across coloumns

            4         3         2         1         0
0    0.879883  0.700803  0.523924  0.205121     0.728
1    0.988455  0.131469  0.358358  0.467700  0.220325
2    0.074826  0.163342  0.814943  0.472727  0.177322
3    0.873583  0.217000  0.272566  0.085368  0.532886
4    0.916849  0.980649  0.567778  0.189538  0.673413
..        ...       ...       ...       ...       ...
329  0.196818  0.781128  0.388197  0.040191  0.444313
330  0.386153  0.984123  0.818672  0.063917   0.63407
331  0.044200  0.227695  0.346433  0.129844  0.294954
332  0.435259  0.047619  0.387504  0.357340  0.452859
333  0.951393  0.690804  0.538841  0.122899  0.076535

[334 rows x 5 columns]

In [161]:
newdf.sort_index(axis=0, ascending=False)
# across rows

            0         1         2         3         4
333  0.076535  0.122899  0.538841  0.690804  0.951393
332  0.452859  0.357340  0.387504  0.047619  0.435259
331  0.294954  0.129844  0.346433  0.227695  0.044200
330   0.63407  0.063917  0.818672  0.984123  0.386153
329  0.444313  0.040191  0.388197  0.781128  0.196818
..        ...       ...       ...       ...       ...
4    0.673413  0.189538  0.567778  0.980649  0.916849
3    0.532886  0.085368  0.272566  0.217000  0.873583
2    0.177322  0.472727  0.814943  0.163342  0.074826
1    0.220325  0.467700  0.358358  0.131469  0.988455
0       0.728  0.205121  0.523924  0.700803  0.879883

[334 rows x 5 columns]

In [162]:
type(newdf[0])

pandas.core.series.Series

In [163]:
newdf2 = newdf
# here newdf2 is the view (pointing to newdf)

In [164]:
newdf2[0][0] = 7283

In [165]:
newdf

            0         1         2         3         4
0        7283  0.205121  0.523924  0.700803  0.879883
1    0.220325  0.467700  0.358358  0.131469  0.988455
2    0.177322  0.472727  0.814943  0.163342  0.074826
3    0.532886  0.085368  0.272566  0.217000  0.873583
4    0.673413  0.189538  0.567778  0.980649  0.916849
..        ...       ...       ...       ...       ...
329  0.444313  0.040191  0.388197  0.781128  0.196818
330   0.63407  0.063917  0.818672  0.984123  0.386153
331  0.294954  0.129844  0.346433  0.227695  0.044200
332  0.452859  0.357340  0.387504  0.047619  0.435259
333  0.076535  0.122899  0.538841  0.690804  0.951393

[334 rows x 5 columns]

In [166]:
newdf3 = newdf.copy()
newdf3[0][0] = 82
newdf

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\575451395.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf3[0][0] = 82
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\575451395.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf3[0][0] = 82

            0         1         2         3         4
0        7283  0.205121  0.523924  0.700803  0.879883
1    0.220325  0.467700  0.358358  0.131469  0.988455
2    0.177322  0.472727  0.814943  0.163342  0.074826
3    0.532886  0.085368  0.272566  0.217000  0.873583
4    0.673413  0.189538  0.567778  0.980649  0.916849
..        ...       ...       ...       ...       ...
329  0.444313  0.040191  0.388197  0.781128  0.196818
330   0.63407  0.063917  0.818672  0.984123  0.386153
331  0.294954  0.129844  0.346433  0.227695  0.044200
332  0.452859  0.357340  0.387504  0.047619  0.435259
333  0.076535  0.122899  0.538841  0.690804  0.951393

[334 rows x 5 columns]

In [167]:
newdf

            0         1         2         3         4
0        7283  0.205121  0.523924  0.700803  0.879883
1    0.220325  0.467700  0.358358  0.131469  0.988455
2    0.177322  0.472727  0.814943  0.163342  0.074826
3    0.532886  0.085368  0.272566  0.217000  0.873583
4    0.673413  0.189538  0.567778  0.980649  0.916849
..        ...       ...       ...       ...       ...
329  0.444313  0.040191  0.388197  0.781128  0.196818
330   0.63407  0.063917  0.818672  0.984123  0.386153
331  0.294954  0.129844  0.346433  0.227695  0.044200
332  0.452859  0.357340  0.387504  0.047619  0.435259
333  0.076535  0.122899  0.538841  0.690804  0.951393

[334 rows x 5 columns]

In [168]:
newdf.loc[0,0] = 26

In [169]:
newdf

            0         1         2         3         4
0          26  0.205121  0.523924  0.700803  0.879883
1    0.220325  0.467700  0.358358  0.131469  0.988455
2    0.177322  0.472727  0.814943  0.163342  0.074826
3    0.532886  0.085368  0.272566  0.217000  0.873583
4    0.673413  0.189538  0.567778  0.980649  0.916849
..        ...       ...       ...       ...       ...
329  0.444313  0.040191  0.388197  0.781128  0.196818
330   0.63407  0.063917  0.818672  0.984123  0.386153
331  0.294954  0.129844  0.346433  0.227695  0.044200
332  0.452859  0.357340  0.387504  0.047619  0.435259
333  0.076535  0.122899  0.538841  0.690804  0.951393

[334 rows x 5 columns]

In [170]:
newdf.columns = list("ABCDE")

In [171]:
newdf

            A         B         C         D         E
0          26  0.205121  0.523924  0.700803  0.879883
1    0.220325  0.467700  0.358358  0.131469  0.988455
2    0.177322  0.472727  0.814943  0.163342  0.074826
3    0.532886  0.085368  0.272566  0.217000  0.873583
4    0.673413  0.189538  0.567778  0.980649  0.916849
..        ...       ...       ...       ...       ...
329  0.444313  0.040191  0.388197  0.781128  0.196818
330   0.63407  0.063917  0.818672  0.984123  0.386153
331  0.294954  0.129844  0.346433  0.227695  0.044200
332  0.452859  0.357340  0.387504  0.047619  0.435259
333  0.076535  0.122899  0.538841  0.690804  0.951393

[334 rows x 5 columns]

In [172]:
newdf = newdf.drop('A', axis=1)  
# changes column
newdf

            B         C         D         E
0    0.205121  0.523924  0.700803  0.879883
1    0.467700  0.358358  0.131469  0.988455
2    0.472727  0.814943  0.163342  0.074826
3    0.085368  0.272566  0.217000  0.873583
4    0.189538  0.567778  0.980649  0.916849
..        ...       ...       ...       ...
329  0.040191  0.388197  0.781128  0.196818
330  0.063917  0.818672  0.984123  0.386153
331  0.129844  0.346433  0.227695  0.044200
332  0.357340  0.387504  0.047619  0.435259
333  0.122899  0.538841  0.690804  0.951393

[334 rows x 4 columns]

In [ ]:
newdf.loc[[1,2], ['C','D']]

          C         D
1  0.358358  0.131469
2  0.814943  0.163342

In [174]:
newdf.head()

          B         C         D         E
0  0.205121  0.523924  0.700803  0.879883
1  0.467700  0.358358  0.131469  0.988455
2  0.472727  0.814943  0.163342  0.074826
3  0.085368  0.272566  0.217000  0.873583
4  0.189538  0.567778  0.980649  0.916849

In [182]:
newdf.loc[[1,2],:]

          B         C         D         E
1  0.467700  0.358358  0.131469  0.988455
2  0.472727  0.814943  0.163342  0.074826

In [184]:
newdf.loc[(newdf['B']<0.3)]

            B         C         D         E
0    0.205121  0.523924  0.700803  0.879883
3    0.085368  0.272566  0.217000  0.873583
4    0.189538  0.567778  0.980649  0.916849
11   0.166990  0.242402  0.877415  0.251472
25   0.031431  0.491132  0.912489  0.881137
..        ...       ...       ...       ...
326  0.013510  0.371377  0.209204  0.390393
329  0.040191  0.388197  0.781128  0.196818
330  0.063917  0.818672  0.984123  0.386153
331  0.129844  0.346433  0.227695  0.044200
333  0.122899  0.538841  0.690804  0.951393

[96 rows x 4 columns]