In [485]:
import numpy as np
import pandas as pd

In [486]:
dict1 = {
    "name": ["kirti", "peter", "sam", "shubh"],
    "marks": [92, 93, 31, 86],
    "city": ["delhi", "calfornia", "goa", "chandigarh"]
}

In [487]:
df = pd.DataFrame(dict1)

In [488]:
print(df)

    name  marks        city
0  kirti     92       delhi
1  peter     93   calfornia
2    sam     31         goa
3  shubh     86  chandigarh

In [489]:
df.to_csv('data.csv')
df.to_csv('data_without_index.csv', index=False)

In [490]:
df.head(2)

    name  marks       city
0  kirti     92      delhi
1  peter     93  calfornia

In [491]:
df.tail(2)

    name  marks        city
2    sam     31         goa
3  shubh     86  chandigarh

In [492]:
df.describe()

           marks
count   4.000000
mean   75.500000
std    29.827281
min    31.000000
25%    72.250000
50%    89.000000
75%    92.250000
max    93.000000

In [493]:
trains = pd.read_csv('trains.csv')

In [494]:
trains

,Unnamed: 0.10,Unnamed: 0.9,Unnamed: 0.8,Unnamed: 0.7,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Train No.,speed,city
0,0,0,0,0,0,0,0,0,0,0,0,12238,50,delhi
1,1,1,1,1,1,1,1,1,1,1,1,38265,28,calfornia
2,2,2,2,2,2,2,2,2,2,2,2,98542,31,goa
3,3,3,3,3,3,3,3,3,3,3,3,17662,86,chandigarh

In [495]:
trains['speed'][0] = 50

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\3155761661.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  trains['speed'][0] = 50
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\3155761661.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trains['speed'][0] = 50

In [496]:
trains

,Unnamed: 0.10,Unnamed: 0.9,Unnamed: 0.8,Unnamed: 0.7,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Train No.,speed,city
0,0,0,0,0,0,0,0,0,0,0,0,12238,50,delhi
1,1,1,1,1,1,1,1,1,1,1,1,38265,28,calfornia
2,2,2,2,2,2,2,2,2,2,2,2,98542,31,goa
3,3,3,3,3,3,3,3,3,3,3,3,17662,86,chandigarh

In [497]:
trains.to_csv('trains.csv')

In [498]:
trains.index = ["first", "second", "third", " fourth"]
trains

,Unnamed: 0.10,Unnamed: 0.9,Unnamed: 0.8,Unnamed: 0.7,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Train No.,speed,city
first,0,0,0,0,0,0,0,0,0,0,0,12238,50,delhi
second,1,1,1,1,1,1,1,1,1,1,1,38265,28,calfornia
third,2,2,2,2,2,2,2,2,2,2,2,98542,31,goa
fourth,3,3,3,3,3,3,3,3,3,3,3,17662,86,chandigarh

In [499]:
ser = pd.Series(np.random.rand(34))
type(ser)
ser

0     0.132417
1     0.699179
2     0.728618
3     0.364975
4     0.450429
5     0.162620
6     0.237939
7     0.612764
8     0.849455
9     0.869433
10    0.163340
11    0.183960
12    0.388467
13    0.016648
14    0.531407
15    0.855567
16    0.665627
17    0.264549
18    0.472955
19    0.941337
20    0.626236
21    0.714361
22    0.635968
23    0.918760
24    0.919077
25    0.144852
26    0.935876
27    0.583371
28    0.851617
29    0.772402
30    0.426869
31    0.724416
32    0.200369
33    0.125791
dtype: float64

In [500]:
newdf = pd.DataFrame(np.random.rand(334, 5), index=np.arange(334))
print(type(newdf))
newdf

<class 'pandas.core.frame.DataFrame'>

            0         1         2         3         4
0    0.306547  0.951370  0.036987  0.619979  0.402808
1    0.969103  0.581523  0.717229  0.474833  0.266211
2    0.045603  0.529193  0.977727  0.327742  0.983919
3    0.165671  0.556494  0.993594  0.295413  0.639949
4    0.005671  0.324671  0.443016  0.905050  0.744989
..        ...       ...       ...       ...       ...
329  0.349788  0.819121  0.450958  0.249573  0.279474
330  0.541727  0.623593  0.973423  0.619906  0.012779
331  0.336678  0.018639  0.956044  0.624677  0.545868
332  0.316079  0.632160  0.631617  0.979670  0.647269
333  0.450389  0.115346  0.275276  0.797554  0.007426

[334 rows x 5 columns]

In [501]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.498751    0.514929    0.499786    0.515860    0.476061
std      0.289151    0.287152    0.287576    0.292805    0.289907
min      0.005671    0.006967    0.002376    0.005338    0.005851
25%      0.254496    0.260469    0.266472    0.266629    0.230313
50%      0.484163    0.535771    0.516695    0.527923    0.465476
75%      0.753447    0.760495    0.741833    0.774625    0.732999
max      0.998971    0.997205    0.999448    0.999625    0.994784

In [502]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [503]:
newdf[0][0] = "kirti"
newdf.head(2)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\2125280267.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0] = "kirti"
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\2125280267.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'kirti' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0] = "kirti"

          0         1         2         3         4
0     kirti  0.951370  0.036987  0.619979  0.402808
1  0.969103  0.581523  0.717229  0.474833  0.266211

In [504]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [505]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [506]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [507]:
newdf.to_numpy()

array([['kirti', 0.951370360780321, 0.036987180623241356,
        0.6199786864425753, 0.40280765383967765],
       [0.9691026155377406, 0.5815231128423757, 0.7172293922000483,
        0.47483294505419427, 0.26621094770373854],
       [0.045603237887826276, 0.5291933143939263, 0.9777267681759098,
        0.32774211669751974, 0.9839188349378999],
       ...,
       [0.3366782128679633, 0.018639076566832502, 0.9560443284660011,
        0.6246772432750769, 0.5458678000220757],
       [0.31607856385929534, 0.6321599499997423, 0.6316173925435237,
        0.9796703048208415, 0.647269343170764],
       [0.4503893364278547, 0.1153461177580708, 0.275275807927434,
        0.7975542083407587, 0.007425987818068802]],
      shape=(334, 5), dtype=object)

In [508]:
newdf[0][0]=0.728
newdf.head(2)

          0         1         2         3         4
0     0.728  0.951370  0.036987  0.619979  0.402808
1  0.969103  0.581523  0.717229  0.474833  0.266211

In [509]:
newdf.to_numpy()

array([[0.728, 0.951370360780321, 0.036987180623241356,
        0.6199786864425753, 0.40280765383967765],
       [0.9691026155377406, 0.5815231128423757, 0.7172293922000483,
        0.47483294505419427, 0.26621094770373854],
       [0.045603237887826276, 0.5291933143939263, 0.9777267681759098,
        0.32774211669751974, 0.9839188349378999],
       ...,
       [0.3366782128679633, 0.018639076566832502, 0.9560443284660011,
        0.6246772432750769, 0.5458678000220757],
       [0.31607856385929534, 0.6321599499997423, 0.6316173925435237,
        0.9796703048208415, 0.647269343170764],
       [0.4503893364278547, 0.1153461177580708, 0.275275807927434,
        0.7975542083407587, 0.007425987818068802]],
      shape=(334, 5), dtype=object)

In [510]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.728,0.969103,0.045603,0.165671,0.005671,0.314615,0.802849,0.734344,0.435098,0.861985,...,0.759052,0.80757,0.961646,0.515881,0.750782,0.349788,0.541727,0.336678,0.316079,0.450389
1,0.95137,0.581523,0.529193,0.556494,0.324671,0.584002,0.568978,0.130197,0.549686,0.192316,...,0.993566,0.89491,0.90559,0.200229,0.356193,0.819121,0.623593,0.018639,0.63216,0.115346
2,0.036987,0.717229,0.977727,0.993594,0.443016,0.619599,0.532029,0.517599,0.49684,0.966347,...,0.307469,0.667534,0.226454,0.725464,0.15843,0.450958,0.973423,0.956044,0.631617,0.275276
3,0.619979,0.474833,0.327742,0.295413,0.90505,0.415128,0.98843,0.00594,0.904557,0.065508,...,0.155758,0.089793,0.876637,0.8536,0.464512,0.249573,0.619906,0.624677,0.97967,0.797554
4,0.402808,0.266211,0.983919,0.639949,0.744989,0.096042,0.309464,0.451158,0.900614,0.848404,...,0.906278,0.230021,0.699415,0.01821,0.884154,0.279474,0.012779,0.545868,0.647269,0.007426

In [511]:
newdf.head()

          0         1         2         3         4
0     0.728  0.951370  0.036987  0.619979  0.402808
1  0.969103  0.581523  0.717229  0.474833  0.266211
2  0.045603  0.529193  0.977727  0.327742  0.983919
3  0.165671  0.556494  0.993594  0.295413  0.639949
4  0.005671  0.324671  0.443016  0.905050  0.744989

In [512]:
newdf.sort_index(axis = 1, ascending=False)
# across coloumns

            4         3         2         1         0
0    0.402808  0.619979  0.036987  0.951370     0.728
1    0.266211  0.474833  0.717229  0.581523  0.969103
2    0.983919  0.327742  0.977727  0.529193  0.045603
3    0.639949  0.295413  0.993594  0.556494  0.165671
4    0.744989  0.905050  0.443016  0.324671  0.005671
..        ...       ...       ...       ...       ...
329  0.279474  0.249573  0.450958  0.819121  0.349788
330  0.012779  0.619906  0.973423  0.623593  0.541727
331  0.545868  0.624677  0.956044  0.018639  0.336678
332  0.647269  0.979670  0.631617  0.632160  0.316079
333  0.007426  0.797554  0.275276  0.115346  0.450389

[334 rows x 5 columns]

In [513]:
newdf.sort_index(axis=0, ascending=False)
# across rows

            0         1         2         3         4
333  0.450389  0.115346  0.275276  0.797554  0.007426
332  0.316079  0.632160  0.631617  0.979670  0.647269
331  0.336678  0.018639  0.956044  0.624677  0.545868
330  0.541727  0.623593  0.973423  0.619906  0.012779
329  0.349788  0.819121  0.450958  0.249573  0.279474
..        ...       ...       ...       ...       ...
4    0.005671  0.324671  0.443016  0.905050  0.744989
3    0.165671  0.556494  0.993594  0.295413  0.639949
2    0.045603  0.529193  0.977727  0.327742  0.983919
1    0.969103  0.581523  0.717229  0.474833  0.266211
0       0.728  0.951370  0.036987  0.619979  0.402808

[334 rows x 5 columns]

In [514]:
type(newdf[0])

pandas.core.series.Series

In [515]:
newdf2 = newdf
# here newdf2 is the view (pointing to newdf)

In [516]:
newdf2[0][0] = 7283

In [517]:
newdf

            0         1         2         3         4
0        7283  0.951370  0.036987  0.619979  0.402808
1    0.969103  0.581523  0.717229  0.474833  0.266211
2    0.045603  0.529193  0.977727  0.327742  0.983919
3    0.165671  0.556494  0.993594  0.295413  0.639949
4    0.005671  0.324671  0.443016  0.905050  0.744989
..        ...       ...       ...       ...       ...
329  0.349788  0.819121  0.450958  0.249573  0.279474
330  0.541727  0.623593  0.973423  0.619906  0.012779
331  0.336678  0.018639  0.956044  0.624677  0.545868
332  0.316079  0.632160  0.631617  0.979670  0.647269
333  0.450389  0.115346  0.275276  0.797554  0.007426

[334 rows x 5 columns]

In [518]:
newdf3 = newdf.copy()
newdf3[0][0] = 82
newdf

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\575451395.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf3[0][0] = 82
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\575451395.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf3[0][0] = 82

            0         1         2         3         4
0        7283  0.951370  0.036987  0.619979  0.402808
1    0.969103  0.581523  0.717229  0.474833  0.266211
2    0.045603  0.529193  0.977727  0.327742  0.983919
3    0.165671  0.556494  0.993594  0.295413  0.639949
4    0.005671  0.324671  0.443016  0.905050  0.744989
..        ...       ...       ...       ...       ...
329  0.349788  0.819121  0.450958  0.249573  0.279474
330  0.541727  0.623593  0.973423  0.619906  0.012779
331  0.336678  0.018639  0.956044  0.624677  0.545868
332  0.316079  0.632160  0.631617  0.979670  0.647269
333  0.450389  0.115346  0.275276  0.797554  0.007426

[334 rows x 5 columns]

In [519]:
newdf

            0         1         2         3         4
0        7283  0.951370  0.036987  0.619979  0.402808
1    0.969103  0.581523  0.717229  0.474833  0.266211
2    0.045603  0.529193  0.977727  0.327742  0.983919
3    0.165671  0.556494  0.993594  0.295413  0.639949
4    0.005671  0.324671  0.443016  0.905050  0.744989
..        ...       ...       ...       ...       ...
329  0.349788  0.819121  0.450958  0.249573  0.279474
330  0.541727  0.623593  0.973423  0.619906  0.012779
331  0.336678  0.018639  0.956044  0.624677  0.545868
332  0.316079  0.632160  0.631617  0.979670  0.647269
333  0.450389  0.115346  0.275276  0.797554  0.007426

[334 rows x 5 columns]

In [520]:
newdf.loc[0,0] = 26
# helps in accessing the values by specifying the position

In [521]:
newdf

            0         1         2         3         4
0          26  0.951370  0.036987  0.619979  0.402808
1    0.969103  0.581523  0.717229  0.474833  0.266211
2    0.045603  0.529193  0.977727  0.327742  0.983919
3    0.165671  0.556494  0.993594  0.295413  0.639949
4    0.005671  0.324671  0.443016  0.905050  0.744989
..        ...       ...       ...       ...       ...
329  0.349788  0.819121  0.450958  0.249573  0.279474
330  0.541727  0.623593  0.973423  0.619906  0.012779
331  0.336678  0.018639  0.956044  0.624677  0.545868
332  0.316079  0.632160  0.631617  0.979670  0.647269
333  0.450389  0.115346  0.275276  0.797554  0.007426

[334 rows x 5 columns]

In [522]:
newdf.columns = list("ABCDE")

In [523]:
newdf

            A         B         C         D         E
0          26  0.951370  0.036987  0.619979  0.402808
1    0.969103  0.581523  0.717229  0.474833  0.266211
2    0.045603  0.529193  0.977727  0.327742  0.983919
3    0.165671  0.556494  0.993594  0.295413  0.639949
4    0.005671  0.324671  0.443016  0.905050  0.744989
..        ...       ...       ...       ...       ...
329  0.349788  0.819121  0.450958  0.249573  0.279474
330  0.541727  0.623593  0.973423  0.619906  0.012779
331  0.336678  0.018639  0.956044  0.624677  0.545868
332  0.316079  0.632160  0.631617  0.979670  0.647269
333  0.450389  0.115346  0.275276  0.797554  0.007426

[334 rows x 5 columns]

In [524]:
newdf = newdf.drop('A', axis=1)  
# changes column
newdf

            B         C         D         E
0    0.951370  0.036987  0.619979  0.402808
1    0.581523  0.717229  0.474833  0.266211
2    0.529193  0.977727  0.327742  0.983919
3    0.556494  0.993594  0.295413  0.639949
4    0.324671  0.443016  0.905050  0.744989
..        ...       ...       ...       ...
329  0.819121  0.450958  0.249573  0.279474
330  0.623593  0.973423  0.619906  0.012779
331  0.018639  0.956044  0.624677  0.545868
332  0.632160  0.631617  0.979670  0.647269
333  0.115346  0.275276  0.797554  0.007426

[334 rows x 4 columns]

In [525]:
newdf.loc[[1,2], ['C','D']]

          C         D
1  0.717229  0.474833
2  0.977727  0.327742

In [526]:
newdf.head()

          B         C         D         E
0  0.951370  0.036987  0.619979  0.402808
1  0.581523  0.717229  0.474833  0.266211
2  0.529193  0.977727  0.327742  0.983919
3  0.556494  0.993594  0.295413  0.639949
4  0.324671  0.443016  0.905050  0.744989

In [527]:
newdf.loc[[1,2],:]

          B         C         D         E
1  0.581523  0.717229  0.474833  0.266211
2  0.529193  0.977727  0.327742  0.983919

In [528]:
newdf.loc[(newdf['B']<0.3)]

            B         C         D         E
7    0.130197  0.517599  0.005940  0.451158
9    0.192316  0.966347  0.065508  0.848404
13   0.156842  0.549493  0.472236  0.845019
14   0.155402  0.285261  0.993635  0.880956
21   0.201934  0.002845  0.613001  0.429042
..        ...       ...       ...       ...
322  0.056312  0.025314  0.999625  0.052918
323  0.116411  0.849848  0.917650  0.070086
327  0.200229  0.725464  0.853600  0.018210
331  0.018639  0.956044  0.624677  0.545868
333  0.115346  0.275276  0.797554  0.007426

[97 rows x 4 columns]

In [529]:
newdf.loc[(newdf['B']<0.3) & (newdf['C']>0.1)]

            B         C         D         E
7    0.130197  0.517599  0.005940  0.451158
9    0.192316  0.966347  0.065508  0.848404
13   0.156842  0.549493  0.472236  0.845019
14   0.155402  0.285261  0.993635  0.880956
23   0.114543  0.382554  0.896455  0.216019
..        ...       ...       ...       ...
318  0.192399  0.395803  0.724073  0.591091
323  0.116411  0.849848  0.917650  0.070086
327  0.200229  0.725464  0.853600  0.018210
331  0.018639  0.956044  0.624677  0.545868
333  0.115346  0.275276  0.797554  0.007426

[84 rows x 4 columns]

In [530]:
newdf.head(8)

          B         C         D         E
0  0.951370  0.036987  0.619979  0.402808
1  0.581523  0.717229  0.474833  0.266211
2  0.529193  0.977727  0.327742  0.983919
3  0.556494  0.993594  0.295413  0.639949
4  0.324671  0.443016  0.905050  0.744989
5  0.584002  0.619599  0.415128  0.096042
6  0.568978  0.532029  0.988430  0.309464
7  0.130197  0.517599  0.005940  0.451158

In [531]:
newdf.iloc[0,3]
# access the value at 0 row, and skips 3 column -> value(0,E)

np.float64(0.40280765383967765)

In [532]:
newdf.iloc[[1,2], [1,2]]

          C         D
1  0.717229  0.474833
2  0.977727  0.327742

In [533]:
newdf.head(3)

          B         C         D         E
0  0.951370  0.036987  0.619979  0.402808
1  0.581523  0.717229  0.474833  0.266211
2  0.529193  0.977727  0.327742  0.983919

In [534]:
# {newdf = newdf.drop('E', axis=1) \n newdf} ==== {newdf.drop('E', axis=1, inplace = True)}

In [535]:
newdf.drop('E', axis=1, inplace = True)

In [536]:
newdf

            B         C         D
0    0.951370  0.036987  0.619979
1    0.581523  0.717229  0.474833
2    0.529193  0.977727  0.327742
3    0.556494  0.993594  0.295413
4    0.324671  0.443016  0.905050
..        ...       ...       ...
329  0.819121  0.450958  0.249573
330  0.623593  0.973423  0.619906
331  0.018639  0.956044  0.624677
332  0.632160  0.631617  0.979670
333  0.115346  0.275276  0.797554

[334 rows x 3 columns]

In [537]:
newdf.head()

          B         C         D
0  0.951370  0.036987  0.619979
1  0.581523  0.717229  0.474833
2  0.529193  0.977727  0.327742
3  0.556494  0.993594  0.295413
4  0.324671  0.443016  0.905050

In [538]:
newdf.drop(0, axis=0, inplace=True)
newdf

            B         C         D
1    0.581523  0.717229  0.474833
2    0.529193  0.977727  0.327742
3    0.556494  0.993594  0.295413
4    0.324671  0.443016  0.905050
5    0.584002  0.619599  0.415128
..        ...       ...       ...
329  0.819121  0.450958  0.249573
330  0.623593  0.973423  0.619906
331  0.018639  0.956044  0.624677
332  0.632160  0.631617  0.979670
333  0.115346  0.275276  0.797554

[333 rows x 3 columns]

In [539]:
newdf.drop(2, axis=0, inplace=True)
newdf

            B         C         D
1    0.581523  0.717229  0.474833
3    0.556494  0.993594  0.295413
4    0.324671  0.443016  0.905050
5    0.584002  0.619599  0.415128
6    0.568978  0.532029  0.988430
..        ...       ...       ...
329  0.819121  0.450958  0.249573
330  0.623593  0.973423  0.619906
331  0.018639  0.956044  0.624677
332  0.632160  0.631617  0.979670
333  0.115346  0.275276  0.797554

[332 rows x 3 columns]

In [540]:
newdf.head()
# destructive indexing

          B         C         D
1  0.581523  0.717229  0.474833
3  0.556494  0.993594  0.295413
4  0.324671  0.443016  0.905050
5  0.584002  0.619599  0.415128
6  0.568978  0.532029  0.988430

In [541]:
newdf.reset_index()

     index         B         C         D
0        1  0.581523  0.717229  0.474833
1        3  0.556494  0.993594  0.295413
2        4  0.324671  0.443016  0.905050
3        5  0.584002  0.619599  0.415128
4        6  0.568978  0.532029  0.988430
..     ...       ...       ...       ...
327    329  0.819121  0.450958  0.249573
328    330  0.623593  0.973423  0.619906
329    331  0.018639  0.956044  0.624677
330    332  0.632160  0.631617  0.979670
331    333  0.115346  0.275276  0.797554

[332 rows x 4 columns]

In [542]:
newdf.reset_index(drop = True, inplace=True)

In [543]:
newdf

            B         C         D
0    0.581523  0.717229  0.474833
1    0.556494  0.993594  0.295413
2    0.324671  0.443016  0.905050
3    0.584002  0.619599  0.415128
4    0.568978  0.532029  0.988430
..        ...       ...       ...
327  0.819121  0.450958  0.249573
328  0.623593  0.973423  0.619906
329  0.018639  0.956044  0.624677
330  0.632160  0.631617  0.979670
331  0.115346  0.275276  0.797554

[332 rows x 3 columns]

In [544]:
newdf.head(3)

          B         C         D
0  0.581523  0.717229  0.474833
1  0.556494  0.993594  0.295413
2  0.324671  0.443016  0.905050

In [545]:
newdf['B'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
327    False
328    False
329    False
330    False
331    False
Name: B, Length: 332, dtype: bool

In [546]:
newdf['B'] = None

In [547]:
newdf['B'].isnull()

0      True
1      True
2      True
3      True
4      True
       ...
327    True
328    True
329    True
330    True
331    True
Name: B, Length: 332, dtype: bool

In [548]:
newdf['B'].notnull()

0      False
1      False
2      False
3      False
4      False
       ...
327    False
328    False
329    False
330    False
331    False
Name: B, Length: 332, dtype: bool

In [549]:
df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
                   "toy": [np.nan, 'Batmobile', 'Bullwhip'],
                   "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT]
                   })

In [550]:
df

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [551]:
df.dropna()

     name        toy       born
1  Batman  Batmobile 1940-04-25

In [552]:
df

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [553]:
df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
                   "toy": [np.nan, np.nan, np.nan],
                   "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT]
                   })

In [554]:
df

       name  toy       born
0    Alfred  NaN        NaT
1    Batman  NaN 1940-04-25
2  Catwoman  NaN        NaT

In [555]:
df.dropna(how="all", axis=1)

       name       born
0    Alfred        NaT
1    Batman 1940-04-25
2  Catwoman        NaT

In [556]:
df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Alfred'],
                   "toy": [np.nan, np.nan, np.nan],
                   "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT]
                   })

In [557]:
df

     name  toy       born
0  Alfred  NaN        NaT
1  Batman  NaN 1940-04-25
2  Alfred  NaN        NaT

In [559]:
df.drop_duplicates(subset=['name'], keep=False)

     name  toy       born
1  Batman  NaN 1940-04-25

In [562]:
df
# keep=False
# inplace=True

     name  toy       born
0  Alfred  NaN        NaT
1  Batman  NaN 1940-04-25
2  Alfred  NaN        NaT

In [564]:
df.shape

(3, 3)

In [566]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   toy     0 non-null      float64
 2   born    1 non-null      datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 204.0+ bytes

In [567]:
df['name'].value_counts(dropna=False)

name
Alfred    2
Batman    1
Name: count, dtype: int64

In [571]:
df['toy'].value_counts(dropna=False)

toy
NaN    3
Name: count, dtype: int64

In [573]:
df['toy'].value_counts(dropna=True)

Series([], Name: count, dtype: int64)