In [574]:
import numpy as np
import pandas as pd

In [575]:
dict1 = {
    "name": ["kirti", "peter", "sam", "shubh"],
    "marks": [92, 93, 31, 86],
    "city": ["delhi", "calfornia", "goa", "chandigarh"]
}

In [576]:
df = pd.DataFrame(dict1)

In [577]:
print(df)

    name  marks        city
0  kirti     92       delhi
1  peter     93   calfornia
2    sam     31         goa
3  shubh     86  chandigarh

In [578]:
df.to_csv('data.csv')
df.to_csv('data_without_index.csv', index=False)

In [579]:
df.head(2)

    name  marks       city
0  kirti     92      delhi
1  peter     93  calfornia

In [580]:
df.tail(2)

    name  marks        city
2    sam     31         goa
3  shubh     86  chandigarh

In [581]:
df.describe()

           marks
count   4.000000
mean   75.500000
std    29.827281
min    31.000000
25%    72.250000
50%    89.000000
75%    92.250000
max    93.000000

In [582]:
trains = pd.read_csv('trains.csv')

In [583]:
trains

,Unnamed: 0.11,Unnamed: 0.10,Unnamed: 0.9,Unnamed: 0.8,Unnamed: 0.7,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Train No.,speed,city
0,0,0,0,0,0,0,0,0,0,0,0,0,12238,50,delhi
1,1,1,1,1,1,1,1,1,1,1,1,1,38265,28,calfornia
2,2,2,2,2,2,2,2,2,2,2,2,2,98542,31,goa
3,3,3,3,3,3,3,3,3,3,3,3,3,17662,86,chandigarh

In [584]:
trains['speed'][0] = 50

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\3155761661.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  trains['speed'][0] = 50
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\3155761661.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trains['speed'][0] = 50

In [585]:
trains

,Unnamed: 0.11,Unnamed: 0.10,Unnamed: 0.9,Unnamed: 0.8,Unnamed: 0.7,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Train No.,speed,city
0,0,0,0,0,0,0,0,0,0,0,0,0,12238,50,delhi
1,1,1,1,1,1,1,1,1,1,1,1,1,38265,28,calfornia
2,2,2,2,2,2,2,2,2,2,2,2,2,98542,31,goa
3,3,3,3,3,3,3,3,3,3,3,3,3,17662,86,chandigarh

In [586]:
trains.to_csv('trains.csv')

In [587]:
trains.index = ["first", "second", "third", " fourth"]
trains

,Unnamed: 0.11,Unnamed: 0.10,Unnamed: 0.9,Unnamed: 0.8,Unnamed: 0.7,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Train No.,speed,city
first,0,0,0,0,0,0,0,0,0,0,0,0,12238,50,delhi
second,1,1,1,1,1,1,1,1,1,1,1,1,38265,28,calfornia
third,2,2,2,2,2,2,2,2,2,2,2,2,98542,31,goa
fourth,3,3,3,3,3,3,3,3,3,3,3,3,17662,86,chandigarh

In [588]:
ser = pd.Series(np.random.rand(34))
type(ser)
ser

0     0.878082
1     0.432456
2     0.989524
3     0.162384
4     0.311081
5     0.140645
6     0.865141
7     0.739811
8     0.765004
9     0.064701
10    0.686729
11    0.475823
12    0.324557
13    0.743489
14    0.470672
15    0.622989
16    0.372635
17    0.964027
18    0.748226
19    0.999408
20    0.416935
21    0.901791
22    0.767042
23    0.080043
24    0.073285
25    0.308999
26    0.637678
27    0.303158
28    0.945078
29    0.119586
30    0.228484
31    0.570265
32    0.998457
33    0.900210
dtype: float64

In [589]:
newdf = pd.DataFrame(np.random.rand(334, 5), index=np.arange(334))
print(type(newdf))
newdf

<class 'pandas.core.frame.DataFrame'>

            0         1         2         3         4
0    0.762291  0.427549  0.129686  0.572998  0.643845
1    0.915343  0.869435  0.919050  0.625746  0.421605
2    0.940516  0.606777  0.348388  0.261359  0.102296
3    0.422537  0.250007  0.284798  0.173240  0.859716
4    0.374715  0.878208  0.524399  0.091547  0.073209
..        ...       ...       ...       ...       ...
329  0.687782  0.153366  0.928951  0.635852  0.072814
330  0.132604  0.341823  0.525888  0.317945  0.395203
331  0.956153  0.349900  0.364449  0.716526  0.186640
332  0.070103  0.923551  0.088718  0.800590  0.183929
333  0.404578  0.883648  0.958795  0.036176  0.505157

[334 rows x 5 columns]

In [590]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.518304    0.512553    0.487838    0.478185    0.499919
std      0.284043    0.296303    0.289879    0.291210    0.288257
min      0.002485    0.000645    0.002773    0.004316    0.002044
25%      0.301861    0.266065    0.245723    0.209361    0.238362
50%      0.525464    0.514377    0.477121    0.467392    0.505204
75%      0.756205    0.774023    0.735821    0.730829    0.762300
max      0.999830    0.997644    0.995309    0.997048    0.985598

In [591]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [592]:
newdf[0][0] = "kirti"
newdf.head(2)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\2125280267.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0] = "kirti"
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\2125280267.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'kirti' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0] = "kirti"

          0         1         2         3         4
0     kirti  0.427549  0.129686  0.572998  0.643845
1  0.915343  0.869435  0.919050  0.625746  0.421605

In [593]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [594]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [595]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [596]:
newdf.to_numpy()

array([['kirti', 0.427548601180047, 0.12968648740807298,
        0.5729980549728013, 0.643845343185977],
       [0.9153428836972212, 0.8694350471018613, 0.9190495465924574,
        0.6257463397294798, 0.42160548417115296],
       [0.9405161285050281, 0.6067766646764741, 0.348387522148895,
        0.26135920747610175, 0.10229614151073951],
       ...,
       [0.9561529937109705, 0.34990031928057186, 0.3644488563519944,
        0.7165261158123951, 0.1866401371664359],
       [0.0701025077699069, 0.9235506004980553, 0.0887181708111987,
        0.8005899220528502, 0.1839291650444479],
       [0.40457818168798976, 0.8836475083949734, 0.9587949330789248,
        0.03617613704197087, 0.5051573995650459]],
      shape=(334, 5), dtype=object)

In [597]:
newdf[0][0]=0.728
newdf.head(2)

          0         1         2         3         4
0     0.728  0.427549  0.129686  0.572998  0.643845
1  0.915343  0.869435  0.919050  0.625746  0.421605

In [598]:
newdf.to_numpy()

array([[0.728, 0.427548601180047, 0.12968648740807298,
        0.5729980549728013, 0.643845343185977],
       [0.9153428836972212, 0.8694350471018613, 0.9190495465924574,
        0.6257463397294798, 0.42160548417115296],
       [0.9405161285050281, 0.6067766646764741, 0.348387522148895,
        0.26135920747610175, 0.10229614151073951],
       ...,
       [0.9561529937109705, 0.34990031928057186, 0.3644488563519944,
        0.7165261158123951, 0.1866401371664359],
       [0.0701025077699069, 0.9235506004980553, 0.0887181708111987,
        0.8005899220528502, 0.1839291650444479],
       [0.40457818168798976, 0.8836475083949734, 0.9587949330789248,
        0.03617613704197087, 0.5051573995650459]],
      shape=(334, 5), dtype=object)

In [599]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.728,0.915343,0.940516,0.422537,0.374715,0.795739,0.006476,0.157142,0.141391,0.718178,...,0.752582,0.345067,0.213765,0.286306,0.398413,0.687782,0.132604,0.956153,0.070103,0.404578
1,0.427549,0.869435,0.606777,0.250007,0.878208,0.820264,0.491779,0.606728,0.79645,0.060138,...,0.271436,0.447775,0.119584,0.978712,0.846207,0.153366,0.341823,0.3499,0.923551,0.883648
2,0.129686,0.91905,0.348388,0.284798,0.524399,0.720803,0.899257,0.636547,0.890766,0.387101,...,0.340924,0.355064,0.138362,0.880051,0.560304,0.928951,0.525888,0.364449,0.088718,0.958795
3,0.572998,0.625746,0.261359,0.17324,0.091547,0.668876,0.792801,0.264193,0.126354,0.46582,...,0.635151,0.427337,0.924978,0.24895,0.308507,0.635852,0.317945,0.716526,0.80059,0.036176
4,0.643845,0.421605,0.102296,0.859716,0.073209,0.303594,0.769585,0.173725,0.490565,0.505251,...,0.445215,0.019326,0.19415,0.807722,0.84196,0.072814,0.395203,0.18664,0.183929,0.505157

In [600]:
newdf.head()

          0         1         2         3         4
0     0.728  0.427549  0.129686  0.572998  0.643845
1  0.915343  0.869435  0.919050  0.625746  0.421605
2  0.940516  0.606777  0.348388  0.261359  0.102296
3  0.422537  0.250007  0.284798  0.173240  0.859716
4  0.374715  0.878208  0.524399  0.091547  0.073209

In [601]:
newdf.sort_index(axis = 1, ascending=False)
# across coloumns

            4         3         2         1         0
0    0.643845  0.572998  0.129686  0.427549     0.728
1    0.421605  0.625746  0.919050  0.869435  0.915343
2    0.102296  0.261359  0.348388  0.606777  0.940516
3    0.859716  0.173240  0.284798  0.250007  0.422537
4    0.073209  0.091547  0.524399  0.878208  0.374715
..        ...       ...       ...       ...       ...
329  0.072814  0.635852  0.928951  0.153366  0.687782
330  0.395203  0.317945  0.525888  0.341823  0.132604
331  0.186640  0.716526  0.364449  0.349900  0.956153
332  0.183929  0.800590  0.088718  0.923551  0.070103
333  0.505157  0.036176  0.958795  0.883648  0.404578

[334 rows x 5 columns]

In [602]:
newdf.sort_index(axis=0, ascending=False)
# across rows

            0         1         2         3         4
333  0.404578  0.883648  0.958795  0.036176  0.505157
332  0.070103  0.923551  0.088718  0.800590  0.183929
331  0.956153  0.349900  0.364449  0.716526  0.186640
330  0.132604  0.341823  0.525888  0.317945  0.395203
329  0.687782  0.153366  0.928951  0.635852  0.072814
..        ...       ...       ...       ...       ...
4    0.374715  0.878208  0.524399  0.091547  0.073209
3    0.422537  0.250007  0.284798  0.173240  0.859716
2    0.940516  0.606777  0.348388  0.261359  0.102296
1    0.915343  0.869435  0.919050  0.625746  0.421605
0       0.728  0.427549  0.129686  0.572998  0.643845

[334 rows x 5 columns]

In [603]:
type(newdf[0])

pandas.core.series.Series

In [604]:
newdf2 = newdf
# here newdf2 is the view (pointing to newdf)

In [605]:
newdf2[0][0] = 7283

In [606]:
newdf

            0         1         2         3         4
0        7283  0.427549  0.129686  0.572998  0.643845
1    0.915343  0.869435  0.919050  0.625746  0.421605
2    0.940516  0.606777  0.348388  0.261359  0.102296
3    0.422537  0.250007  0.284798  0.173240  0.859716
4    0.374715  0.878208  0.524399  0.091547  0.073209
..        ...       ...       ...       ...       ...
329  0.687782  0.153366  0.928951  0.635852  0.072814
330  0.132604  0.341823  0.525888  0.317945  0.395203
331  0.956153  0.349900  0.364449  0.716526  0.186640
332  0.070103  0.923551  0.088718  0.800590  0.183929
333  0.404578  0.883648  0.958795  0.036176  0.505157

[334 rows x 5 columns]

In [607]:
newdf3 = newdf.copy()
newdf3[0][0] = 82
newdf

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\575451395.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf3[0][0] = 82
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\575451395.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf3[0][0] = 82

            0         1         2         3         4
0        7283  0.427549  0.129686  0.572998  0.643845
1    0.915343  0.869435  0.919050  0.625746  0.421605
2    0.940516  0.606777  0.348388  0.261359  0.102296
3    0.422537  0.250007  0.284798  0.173240  0.859716
4    0.374715  0.878208  0.524399  0.091547  0.073209
..        ...       ...       ...       ...       ...
329  0.687782  0.153366  0.928951  0.635852  0.072814
330  0.132604  0.341823  0.525888  0.317945  0.395203
331  0.956153  0.349900  0.364449  0.716526  0.186640
332  0.070103  0.923551  0.088718  0.800590  0.183929
333  0.404578  0.883648  0.958795  0.036176  0.505157

[334 rows x 5 columns]

In [608]:
newdf

            0         1         2         3         4
0        7283  0.427549  0.129686  0.572998  0.643845
1    0.915343  0.869435  0.919050  0.625746  0.421605
2    0.940516  0.606777  0.348388  0.261359  0.102296
3    0.422537  0.250007  0.284798  0.173240  0.859716
4    0.374715  0.878208  0.524399  0.091547  0.073209
..        ...       ...       ...       ...       ...
329  0.687782  0.153366  0.928951  0.635852  0.072814
330  0.132604  0.341823  0.525888  0.317945  0.395203
331  0.956153  0.349900  0.364449  0.716526  0.186640
332  0.070103  0.923551  0.088718  0.800590  0.183929
333  0.404578  0.883648  0.958795  0.036176  0.505157

[334 rows x 5 columns]

In [609]:
newdf.loc[0,0] = 26
# helps in accessing the values by specifying the position

In [610]:
newdf

            0         1         2         3         4
0          26  0.427549  0.129686  0.572998  0.643845
1    0.915343  0.869435  0.919050  0.625746  0.421605
2    0.940516  0.606777  0.348388  0.261359  0.102296
3    0.422537  0.250007  0.284798  0.173240  0.859716
4    0.374715  0.878208  0.524399  0.091547  0.073209
..        ...       ...       ...       ...       ...
329  0.687782  0.153366  0.928951  0.635852  0.072814
330  0.132604  0.341823  0.525888  0.317945  0.395203
331  0.956153  0.349900  0.364449  0.716526  0.186640
332  0.070103  0.923551  0.088718  0.800590  0.183929
333  0.404578  0.883648  0.958795  0.036176  0.505157

[334 rows x 5 columns]

In [611]:
newdf.columns = list("ABCDE")

In [612]:
newdf

            A         B         C         D         E
0          26  0.427549  0.129686  0.572998  0.643845
1    0.915343  0.869435  0.919050  0.625746  0.421605
2    0.940516  0.606777  0.348388  0.261359  0.102296
3    0.422537  0.250007  0.284798  0.173240  0.859716
4    0.374715  0.878208  0.524399  0.091547  0.073209
..        ...       ...       ...       ...       ...
329  0.687782  0.153366  0.928951  0.635852  0.072814
330  0.132604  0.341823  0.525888  0.317945  0.395203
331  0.956153  0.349900  0.364449  0.716526  0.186640
332  0.070103  0.923551  0.088718  0.800590  0.183929
333  0.404578  0.883648  0.958795  0.036176  0.505157

[334 rows x 5 columns]

In [613]:
newdf = newdf.drop('A', axis=1)  
# changes column
newdf

            B         C         D         E
0    0.427549  0.129686  0.572998  0.643845
1    0.869435  0.919050  0.625746  0.421605
2    0.606777  0.348388  0.261359  0.102296
3    0.250007  0.284798  0.173240  0.859716
4    0.878208  0.524399  0.091547  0.073209
..        ...       ...       ...       ...
329  0.153366  0.928951  0.635852  0.072814
330  0.341823  0.525888  0.317945  0.395203
331  0.349900  0.364449  0.716526  0.186640
332  0.923551  0.088718  0.800590  0.183929
333  0.883648  0.958795  0.036176  0.505157

[334 rows x 4 columns]

In [614]:
newdf.loc[[1,2], ['C','D']]

          C         D
1  0.919050  0.625746
2  0.348388  0.261359

In [615]:
newdf.head()

          B         C         D         E
0  0.427549  0.129686  0.572998  0.643845
1  0.869435  0.919050  0.625746  0.421605
2  0.606777  0.348388  0.261359  0.102296
3  0.250007  0.284798  0.173240  0.859716
4  0.878208  0.524399  0.091547  0.073209

In [616]:
newdf.loc[[1,2],:]

          B         C         D         E
1  0.869435  0.919050  0.625746  0.421605
2  0.606777  0.348388  0.261359  0.102296

In [617]:
newdf.loc[(newdf['B']<0.3)]

            B         C         D         E
3    0.250007  0.284798  0.173240  0.859716
9    0.060138  0.387101  0.465820  0.505251
11   0.079406  0.837663  0.178669  0.723956
12   0.037220  0.151634  0.094666  0.802277
21   0.096526  0.230628  0.864441  0.279959
..        ...       ...       ...       ...
321  0.218601  0.553355  0.132048  0.386312
323  0.072416  0.716115  0.184669  0.869981
324  0.271436  0.340924  0.635151  0.445215
326  0.119584  0.138362  0.924978  0.194150
329  0.153366  0.928951  0.635852  0.072814

[98 rows x 4 columns]

In [618]:
newdf.loc[(newdf['B']<0.3) & (newdf['C']>0.1)]

            B         C         D         E
3    0.250007  0.284798  0.173240  0.859716
9    0.060138  0.387101  0.465820  0.505251
11   0.079406  0.837663  0.178669  0.723956
12   0.037220  0.151634  0.094666  0.802277
21   0.096526  0.230628  0.864441  0.279959
..        ...       ...       ...       ...
321  0.218601  0.553355  0.132048  0.386312
323  0.072416  0.716115  0.184669  0.869981
324  0.271436  0.340924  0.635151  0.445215
326  0.119584  0.138362  0.924978  0.194150
329  0.153366  0.928951  0.635852  0.072814

[88 rows x 4 columns]

In [619]:
newdf.head(8)

          B         C         D         E
0  0.427549  0.129686  0.572998  0.643845
1  0.869435  0.919050  0.625746  0.421605
2  0.606777  0.348388  0.261359  0.102296
3  0.250007  0.284798  0.173240  0.859716
4  0.878208  0.524399  0.091547  0.073209
5  0.820264  0.720803  0.668876  0.303594
6  0.491779  0.899257  0.792801  0.769585
7  0.606728  0.636547  0.264193  0.173725

In [620]:
newdf.iloc[0,3]
# access the value at 0 row, and skips 3 column -> value(0,E)

np.float64(0.643845343185977)

In [621]:
newdf.iloc[[1,2], [1,2]]

          C         D
1  0.919050  0.625746
2  0.348388  0.261359

In [622]:
newdf.head(3)

          B         C         D         E
0  0.427549  0.129686  0.572998  0.643845
1  0.869435  0.919050  0.625746  0.421605
2  0.606777  0.348388  0.261359  0.102296

In [623]:
# {newdf = newdf.drop('E', axis=1) \n newdf} ==== {newdf.drop('E', axis=1, inplace = True)}

In [624]:
newdf.drop('E', axis=1, inplace = True)

In [625]:
newdf

            B         C         D
0    0.427549  0.129686  0.572998
1    0.869435  0.919050  0.625746
2    0.606777  0.348388  0.261359
3    0.250007  0.284798  0.173240
4    0.878208  0.524399  0.091547
..        ...       ...       ...
329  0.153366  0.928951  0.635852
330  0.341823  0.525888  0.317945
331  0.349900  0.364449  0.716526
332  0.923551  0.088718  0.800590
333  0.883648  0.958795  0.036176

[334 rows x 3 columns]

In [626]:
newdf.head()

          B         C         D
0  0.427549  0.129686  0.572998
1  0.869435  0.919050  0.625746
2  0.606777  0.348388  0.261359
3  0.250007  0.284798  0.173240
4  0.878208  0.524399  0.091547

In [627]:
newdf.drop(0, axis=0, inplace=True)
newdf

            B         C         D
1    0.869435  0.919050  0.625746
2    0.606777  0.348388  0.261359
3    0.250007  0.284798  0.173240
4    0.878208  0.524399  0.091547
5    0.820264  0.720803  0.668876
..        ...       ...       ...
329  0.153366  0.928951  0.635852
330  0.341823  0.525888  0.317945
331  0.349900  0.364449  0.716526
332  0.923551  0.088718  0.800590
333  0.883648  0.958795  0.036176

[333 rows x 3 columns]

In [628]:
newdf.drop(2, axis=0, inplace=True)
newdf

            B         C         D
1    0.869435  0.919050  0.625746
3    0.250007  0.284798  0.173240
4    0.878208  0.524399  0.091547
5    0.820264  0.720803  0.668876
6    0.491779  0.899257  0.792801
..        ...       ...       ...
329  0.153366  0.928951  0.635852
330  0.341823  0.525888  0.317945
331  0.349900  0.364449  0.716526
332  0.923551  0.088718  0.800590
333  0.883648  0.958795  0.036176

[332 rows x 3 columns]

In [629]:
newdf.head()
# destructive indexing

          B         C         D
1  0.869435  0.919050  0.625746
3  0.250007  0.284798  0.173240
4  0.878208  0.524399  0.091547
5  0.820264  0.720803  0.668876
6  0.491779  0.899257  0.792801

In [630]:
newdf.reset_index()

     index         B         C         D
0        1  0.869435  0.919050  0.625746
1        3  0.250007  0.284798  0.173240
2        4  0.878208  0.524399  0.091547
3        5  0.820264  0.720803  0.668876
4        6  0.491779  0.899257  0.792801
..     ...       ...       ...       ...
327    329  0.153366  0.928951  0.635852
328    330  0.341823  0.525888  0.317945
329    331  0.349900  0.364449  0.716526
330    332  0.923551  0.088718  0.800590
331    333  0.883648  0.958795  0.036176

[332 rows x 4 columns]

In [631]:
newdf.reset_index(drop = True, inplace=True)

In [632]:
newdf

            B         C         D
0    0.869435  0.919050  0.625746
1    0.250007  0.284798  0.173240
2    0.878208  0.524399  0.091547
3    0.820264  0.720803  0.668876
4    0.491779  0.899257  0.792801
..        ...       ...       ...
327  0.153366  0.928951  0.635852
328  0.341823  0.525888  0.317945
329  0.349900  0.364449  0.716526
330  0.923551  0.088718  0.800590
331  0.883648  0.958795  0.036176

[332 rows x 3 columns]

In [633]:
newdf.head(3)

          B         C         D
0  0.869435  0.919050  0.625746
1  0.250007  0.284798  0.173240
2  0.878208  0.524399  0.091547

In [634]:
newdf['B'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
327    False
328    False
329    False
330    False
331    False
Name: B, Length: 332, dtype: bool

In [635]:
newdf['B'] = None

In [636]:
newdf['B'].isnull()

0      True
1      True
2      True
3      True
4      True
       ...
327    True
328    True
329    True
330    True
331    True
Name: B, Length: 332, dtype: bool

In [637]:
newdf['B'].notnull()

0      False
1      False
2      False
3      False
4      False
       ...
327    False
328    False
329    False
330    False
331    False
Name: B, Length: 332, dtype: bool

In [638]:
df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
                   "toy": [np.nan, 'Batmobile', 'Bullwhip'],
                   "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT]
                   })

In [639]:
df

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [640]:
df.dropna()

     name        toy       born
1  Batman  Batmobile 1940-04-25

In [641]:
df

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [642]:
df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
                   "toy": [np.nan, np.nan, np.nan],
                   "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT]
                   })

In [643]:
df

       name  toy       born
0    Alfred  NaN        NaT
1    Batman  NaN 1940-04-25
2  Catwoman  NaN        NaT

In [644]:
df.dropna(how="all", axis=1)

       name       born
0    Alfred        NaT
1    Batman 1940-04-25
2  Catwoman        NaT

In [645]:
df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Alfred'],
                   "toy": [np.nan, np.nan, np.nan],
                   "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT]
                   })

In [646]:
df

     name  toy       born
0  Alfred  NaN        NaT
1  Batman  NaN 1940-04-25
2  Alfred  NaN        NaT

In [647]:
df.drop_duplicates(subset=['name'], keep=False)

     name  toy       born
1  Batman  NaN 1940-04-25

In [648]:
df
# keep=False
# inplace=True

     name  toy       born
0  Alfred  NaN        NaT
1  Batman  NaN 1940-04-25
2  Alfred  NaN        NaT

In [649]:
df.shape

(3, 3)

In [650]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   toy     0 non-null      float64
 2   born    1 non-null      datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 204.0+ bytes

In [651]:
df['name'].value_counts(dropna=False)

name
Alfred    2
Batman    1
Name: count, dtype: int64

In [652]:
df['toy'].value_counts(dropna=False)

toy
NaN    3
Name: count, dtype: int64

In [653]:
df['toy'].value_counts(dropna=True)

Series([], Name: count, dtype: int64)

In [654]:
# create a dataframe with integers only with 3 rows and 2 columns and perform-
# df.describe()
# df.mean()
# df.corr()
# df.count()
# df.max()
# df.min()
# df.median()
# df.std()

In [655]:
sample = pd.DataFrame(np.random.rand(3,2), index=np.arange(3))
sample

          0         1
0  0.007806  0.893715
1  0.157123  0.078656
2  0.925504  0.647730

In [657]:
sample.describe()

              0         1
count  3.000000  3.000000
mean   0.363478  0.540034
std    0.492422  0.418066
min    0.007806  0.078656
25%    0.082464  0.363193
50%    0.157123  0.647730
75%    0.541314  0.770722
max    0.925504  0.893715

In [658]:
sample.mean()

0    0.363478
1    0.540034
dtype: float64

In [659]:
sample.min()

0    0.007806
1    0.078656
dtype: float64

In [660]:
sample.max()

0    0.925504
1    0.893715
dtype: float64

In [661]:
sample.corr()

         0        1
0  1.00000  0.07272
1  0.07272  1.00000

In [662]:
sample.count()

0    3
1    3
dtype: int64

In [663]:
sample.std()

0    0.492422
1    0.418066
dtype: float64

In [665]:
sample.median()

0    0.157123
1    0.647730
dtype: float64

In [668]:
data = pd.read_excel('excel.xlsx')
# otherwise- pip install xlrd

In [669]:
data

   Unnamed: 0  Train No.  speed        city
0           0      12238     50       delhi
1           1      38265     28   calfornia
2           2      98542     31         goa
3           3      17662     86  chandigarh

In [670]:
data.iloc[0,0]=34

In [671]:
data.head()

   Unnamed: 0  Train No.  speed        city
0          34      12238     50       delhi
1           1      38265     28   calfornia
2           2      98542     31         goa
3           3      17662     86  chandigarh

In [673]:
data.to_excel('excel.xlsx')