In [322]:
import numpy as np
import pandas as pd

In [323]:
dict1 = {
    "name": ["kirti", "peter", "sam", "shubh"],
    "marks": [92, 93, 31, 86],
    "city": ["delhi", "calfornia", "goa", "chandigarh"]
}

In [324]:
df = pd.DataFrame(dict1)

In [325]:
print(df)

    name  marks        city
0  kirti     92       delhi
1  peter     93   calfornia
2    sam     31         goa
3  shubh     86  chandigarh

In [326]:
df.to_csv('data.csv')
df.to_csv('data_without_index.csv', index=False)

In [327]:
df.head(2)

    name  marks       city
0  kirti     92      delhi
1  peter     93  calfornia

In [328]:
df.tail(2)

    name  marks        city
2    sam     31         goa
3  shubh     86  chandigarh

In [329]:
df.describe()

           marks
count   4.000000
mean   75.500000
std    29.827281
min    31.000000
25%    72.250000
50%    89.000000
75%    92.250000
max    93.000000

In [330]:
trains = pd.read_csv('trains.csv')

In [331]:
trains

,Unnamed: 0.8,Unnamed: 0.7,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Train No.,speed,city
0,0,0,0,0,0,0,0,0,0,12238,50,delhi
1,1,1,1,1,1,1,1,1,1,38265,28,calfornia
2,2,2,2,2,2,2,2,2,2,98542,31,goa
3,3,3,3,3,3,3,3,3,3,17662,86,chandigarh

In [332]:
trains['speed'][0] = 50

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\3155761661.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  trains['speed'][0] = 50
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\3155761661.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trains['speed'][0] = 50

In [333]:
trains

,Unnamed: 0.8,Unnamed: 0.7,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Train No.,speed,city
0,0,0,0,0,0,0,0,0,0,12238,50,delhi
1,1,1,1,1,1,1,1,1,1,38265,28,calfornia
2,2,2,2,2,2,2,2,2,2,98542,31,goa
3,3,3,3,3,3,3,3,3,3,17662,86,chandigarh

In [334]:
trains.to_csv('trains.csv')

In [335]:
trains.index = ["first", "second", "third", " fourth"]
trains

,Unnamed: 0.8,Unnamed: 0.7,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Train No.,speed,city
first,0,0,0,0,0,0,0,0,0,12238,50,delhi
second,1,1,1,1,1,1,1,1,1,38265,28,calfornia
third,2,2,2,2,2,2,2,2,2,98542,31,goa
fourth,3,3,3,3,3,3,3,3,3,17662,86,chandigarh

In [336]:
ser = pd.Series(np.random.rand(34))
type(ser)
ser

0     0.757627
1     0.298632
2     0.103745
3     0.403122
4     0.063694
5     0.022575
6     0.161810
7     0.347222
8     0.353337
9     0.462294
10    0.076651
11    0.524079
12    0.319396
13    0.059694
14    0.907451
15    0.293556
16    0.877281
17    0.451169
18    0.883581
19    0.266745
20    0.719621
21    0.873662
22    0.425992
23    0.415001
24    0.152180
25    0.630714
26    0.962661
27    0.352058
28    0.279321
29    0.483034
30    0.941209
31    0.575292
32    0.118056
33    0.265087
dtype: float64

In [337]:
newdf = pd.DataFrame(np.random.rand(334, 5), index=np.arange(334))
print(type(newdf))
newdf

<class 'pandas.core.frame.DataFrame'>

            0         1         2         3         4
0    0.435743  0.352351  0.357062  0.964179  0.485695
1    0.444827  0.367116  0.879366  0.852277  0.843361
2    0.079454  0.074232  0.702791  0.470291  0.885208
3    0.181509  0.790092  0.129039  0.273185  0.012465
4    0.045787  0.128046  0.552759  0.107119  0.846524
..        ...       ...       ...       ...       ...
329  0.993641  0.841470  0.114174  0.916132  0.648312
330  0.614136  0.161234  0.996332  0.895766  0.805775
331  0.915478  0.882787  0.889840  0.413767  0.055343
332  0.589867  0.329925  0.257853  0.192152  0.564785
333  0.315955  0.469750  0.955389  0.225426  0.250093

[334 rows x 5 columns]

In [338]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.484693    0.507011    0.490848    0.490724    0.506246
std      0.295503    0.294973    0.278474    0.289701    0.294358
min      0.002615    0.002264    0.003685    0.004780    0.001379
25%      0.224654    0.248257    0.237312    0.232984    0.244671
50%      0.456671    0.506098    0.481132    0.487220    0.517697
75%      0.727705    0.781377    0.740248    0.745109    0.745978
max      0.996133    0.998338    0.996332    0.995646    0.995618

In [339]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [340]:
newdf[0][0] = "kirti"
newdf.head(2)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\2125280267.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0] = "kirti"
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\2125280267.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'kirti' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0] = "kirti"

          0         1         2         3         4
0     kirti  0.352351  0.357062  0.964179  0.485695
1  0.444827  0.367116  0.879366  0.852277  0.843361

In [341]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [342]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [343]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [344]:
newdf.to_numpy()

array([['kirti', 0.35235063030650593, 0.3570618896202692,
        0.964179110206087, 0.4856947873295141],
       [0.44482742602344016, 0.36711563443068573, 0.8793662927550604,
        0.8522774662776927, 0.84336082188825],
       [0.07945368704743716, 0.07423227488016504, 0.7027906923076532,
        0.4702905109535265, 0.8852077880607911],
       ...,
       [0.9154783264602303, 0.8827873651342664, 0.8898396500355868,
        0.41376672236809475, 0.05534252415399443],
       [0.589867141838347, 0.32992509960193817, 0.2578531299863237,
        0.19215185337684482, 0.5647850095549624],
       [0.3159546791973682, 0.4697504380261499, 0.9553894438249249,
        0.2254256823663523, 0.2500933971226712]],
      shape=(334, 5), dtype=object)

In [345]:
newdf[0][0]=0.728
newdf.head(2)

          0         1         2         3         4
0     0.728  0.352351  0.357062  0.964179  0.485695
1  0.444827  0.367116  0.879366  0.852277  0.843361

In [346]:
newdf.to_numpy()

array([[0.728, 0.35235063030650593, 0.3570618896202692,
        0.964179110206087, 0.4856947873295141],
       [0.44482742602344016, 0.36711563443068573, 0.8793662927550604,
        0.8522774662776927, 0.84336082188825],
       [0.07945368704743716, 0.07423227488016504, 0.7027906923076532,
        0.4702905109535265, 0.8852077880607911],
       ...,
       [0.9154783264602303, 0.8827873651342664, 0.8898396500355868,
        0.41376672236809475, 0.05534252415399443],
       [0.589867141838347, 0.32992509960193817, 0.2578531299863237,
        0.19215185337684482, 0.5647850095549624],
       [0.3159546791973682, 0.4697504380261499, 0.9553894438249249,
        0.2254256823663523, 0.2500933971226712]],
      shape=(334, 5), dtype=object)

In [347]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.728,0.444827,0.079454,0.181509,0.045787,0.553651,0.530771,0.143116,0.647046,0.720098,...,0.42272,0.571406,0.780972,0.968126,0.265367,0.993641,0.614136,0.915478,0.589867,0.315955
1,0.352351,0.367116,0.074232,0.790092,0.128046,0.998338,0.334803,0.175055,0.970712,0.875345,...,0.238019,0.878247,0.706928,0.664193,0.541297,0.84147,0.161234,0.882787,0.329925,0.46975
2,0.357062,0.879366,0.702791,0.129039,0.552759,0.425079,0.237268,0.863545,0.151377,0.784129,...,0.304172,0.419613,0.710035,0.507307,0.041728,0.114174,0.996332,0.88984,0.257853,0.955389
3,0.964179,0.852277,0.470291,0.273185,0.107119,0.296949,0.893267,0.14451,0.339143,0.065165,...,0.070978,0.498101,0.26207,0.218207,0.605673,0.916132,0.895766,0.413767,0.192152,0.225426
4,0.485695,0.843361,0.885208,0.012465,0.846524,0.63255,0.684325,0.07041,0.139423,0.719745,...,0.476991,0.981904,0.208378,0.790983,0.891243,0.648312,0.805775,0.055343,0.564785,0.250093

In [348]:
newdf.head()

          0         1         2         3         4
0     0.728  0.352351  0.357062  0.964179  0.485695
1  0.444827  0.367116  0.879366  0.852277  0.843361
2  0.079454  0.074232  0.702791  0.470291  0.885208
3  0.181509  0.790092  0.129039  0.273185  0.012465
4  0.045787  0.128046  0.552759  0.107119  0.846524

In [349]:
newdf.sort_index(axis = 1, ascending=False)
# across coloumns

            4         3         2         1         0
0    0.485695  0.964179  0.357062  0.352351     0.728
1    0.843361  0.852277  0.879366  0.367116  0.444827
2    0.885208  0.470291  0.702791  0.074232  0.079454
3    0.012465  0.273185  0.129039  0.790092  0.181509
4    0.846524  0.107119  0.552759  0.128046  0.045787
..        ...       ...       ...       ...       ...
329  0.648312  0.916132  0.114174  0.841470  0.993641
330  0.805775  0.895766  0.996332  0.161234  0.614136
331  0.055343  0.413767  0.889840  0.882787  0.915478
332  0.564785  0.192152  0.257853  0.329925  0.589867
333  0.250093  0.225426  0.955389  0.469750  0.315955

[334 rows x 5 columns]

In [350]:
newdf.sort_index(axis=0, ascending=False)
# across rows

            0         1         2         3         4
333  0.315955  0.469750  0.955389  0.225426  0.250093
332  0.589867  0.329925  0.257853  0.192152  0.564785
331  0.915478  0.882787  0.889840  0.413767  0.055343
330  0.614136  0.161234  0.996332  0.895766  0.805775
329  0.993641  0.841470  0.114174  0.916132  0.648312
..        ...       ...       ...       ...       ...
4    0.045787  0.128046  0.552759  0.107119  0.846524
3    0.181509  0.790092  0.129039  0.273185  0.012465
2    0.079454  0.074232  0.702791  0.470291  0.885208
1    0.444827  0.367116  0.879366  0.852277  0.843361
0       0.728  0.352351  0.357062  0.964179  0.485695

[334 rows x 5 columns]

In [351]:
type(newdf[0])

pandas.core.series.Series

In [352]:
newdf2 = newdf
# here newdf2 is the view (pointing to newdf)

In [353]:
newdf2[0][0] = 7283

In [354]:
newdf

            0         1         2         3         4
0        7283  0.352351  0.357062  0.964179  0.485695
1    0.444827  0.367116  0.879366  0.852277  0.843361
2    0.079454  0.074232  0.702791  0.470291  0.885208
3    0.181509  0.790092  0.129039  0.273185  0.012465
4    0.045787  0.128046  0.552759  0.107119  0.846524
..        ...       ...       ...       ...       ...
329  0.993641  0.841470  0.114174  0.916132  0.648312
330  0.614136  0.161234  0.996332  0.895766  0.805775
331  0.915478  0.882787  0.889840  0.413767  0.055343
332  0.589867  0.329925  0.257853  0.192152  0.564785
333  0.315955  0.469750  0.955389  0.225426  0.250093

[334 rows x 5 columns]

In [355]:
newdf3 = newdf.copy()
newdf3[0][0] = 82
newdf

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\575451395.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf3[0][0] = 82
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\575451395.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf3[0][0] = 82

            0         1         2         3         4
0        7283  0.352351  0.357062  0.964179  0.485695
1    0.444827  0.367116  0.879366  0.852277  0.843361
2    0.079454  0.074232  0.702791  0.470291  0.885208
3    0.181509  0.790092  0.129039  0.273185  0.012465
4    0.045787  0.128046  0.552759  0.107119  0.846524
..        ...       ...       ...       ...       ...
329  0.993641  0.841470  0.114174  0.916132  0.648312
330  0.614136  0.161234  0.996332  0.895766  0.805775
331  0.915478  0.882787  0.889840  0.413767  0.055343
332  0.589867  0.329925  0.257853  0.192152  0.564785
333  0.315955  0.469750  0.955389  0.225426  0.250093

[334 rows x 5 columns]

In [356]:
newdf

            0         1         2         3         4
0        7283  0.352351  0.357062  0.964179  0.485695
1    0.444827  0.367116  0.879366  0.852277  0.843361
2    0.079454  0.074232  0.702791  0.470291  0.885208
3    0.181509  0.790092  0.129039  0.273185  0.012465
4    0.045787  0.128046  0.552759  0.107119  0.846524
..        ...       ...       ...       ...       ...
329  0.993641  0.841470  0.114174  0.916132  0.648312
330  0.614136  0.161234  0.996332  0.895766  0.805775
331  0.915478  0.882787  0.889840  0.413767  0.055343
332  0.589867  0.329925  0.257853  0.192152  0.564785
333  0.315955  0.469750  0.955389  0.225426  0.250093

[334 rows x 5 columns]

In [357]:
newdf.loc[0,0] = 26
# helps in accessing the values by specifying the position

In [358]:
newdf

            0         1         2         3         4
0          26  0.352351  0.357062  0.964179  0.485695
1    0.444827  0.367116  0.879366  0.852277  0.843361
2    0.079454  0.074232  0.702791  0.470291  0.885208
3    0.181509  0.790092  0.129039  0.273185  0.012465
4    0.045787  0.128046  0.552759  0.107119  0.846524
..        ...       ...       ...       ...       ...
329  0.993641  0.841470  0.114174  0.916132  0.648312
330  0.614136  0.161234  0.996332  0.895766  0.805775
331  0.915478  0.882787  0.889840  0.413767  0.055343
332  0.589867  0.329925  0.257853  0.192152  0.564785
333  0.315955  0.469750  0.955389  0.225426  0.250093

[334 rows x 5 columns]

In [359]:
newdf.columns = list("ABCDE")

In [360]:
newdf

            A         B         C         D         E
0          26  0.352351  0.357062  0.964179  0.485695
1    0.444827  0.367116  0.879366  0.852277  0.843361
2    0.079454  0.074232  0.702791  0.470291  0.885208
3    0.181509  0.790092  0.129039  0.273185  0.012465
4    0.045787  0.128046  0.552759  0.107119  0.846524
..        ...       ...       ...       ...       ...
329  0.993641  0.841470  0.114174  0.916132  0.648312
330  0.614136  0.161234  0.996332  0.895766  0.805775
331  0.915478  0.882787  0.889840  0.413767  0.055343
332  0.589867  0.329925  0.257853  0.192152  0.564785
333  0.315955  0.469750  0.955389  0.225426  0.250093

[334 rows x 5 columns]

In [361]:
newdf = newdf.drop('A', axis=1)  
# changes column
newdf

            B         C         D         E
0    0.352351  0.357062  0.964179  0.485695
1    0.367116  0.879366  0.852277  0.843361
2    0.074232  0.702791  0.470291  0.885208
3    0.790092  0.129039  0.273185  0.012465
4    0.128046  0.552759  0.107119  0.846524
..        ...       ...       ...       ...
329  0.841470  0.114174  0.916132  0.648312
330  0.161234  0.996332  0.895766  0.805775
331  0.882787  0.889840  0.413767  0.055343
332  0.329925  0.257853  0.192152  0.564785
333  0.469750  0.955389  0.225426  0.250093

[334 rows x 4 columns]

In [362]:
newdf.loc[[1,2], ['C','D']]

          C         D
1  0.879366  0.852277
2  0.702791  0.470291

In [363]:
newdf.head()

          B         C         D         E
0  0.352351  0.357062  0.964179  0.485695
1  0.367116  0.879366  0.852277  0.843361
2  0.074232  0.702791  0.470291  0.885208
3  0.790092  0.129039  0.273185  0.012465
4  0.128046  0.552759  0.107119  0.846524

In [364]:
newdf.loc[[1,2],:]

          B         C         D         E
1  0.367116  0.879366  0.852277  0.843361
2  0.074232  0.702791  0.470291  0.885208

In [365]:
newdf.loc[(newdf['B']<0.3)]

            B         C         D         E
2    0.074232  0.702791  0.470291  0.885208
4    0.128046  0.552759  0.107119  0.846524
7    0.175055  0.863545  0.144510  0.070410
15   0.296856  0.900114  0.481028  0.950971
19   0.172539  0.668602  0.725053  0.235907
..        ...       ...       ...       ...
316  0.129801  0.361779  0.725947  0.368529
317  0.273104  0.326747  0.959994  0.343448
319  0.009247  0.516483  0.953229  0.733671
324  0.238019  0.304172  0.070978  0.476991
330  0.161234  0.996332  0.895766  0.805775

[101 rows x 4 columns]

In [366]:
newdf.loc[(newdf['B']<0.3) & (newdf['C']>0.1)]

            B         C         D         E
2    0.074232  0.702791  0.470291  0.885208
4    0.128046  0.552759  0.107119  0.846524
7    0.175055  0.863545  0.144510  0.070410
15   0.296856  0.900114  0.481028  0.950971
19   0.172539  0.668602  0.725053  0.235907
..        ...       ...       ...       ...
316  0.129801  0.361779  0.725947  0.368529
317  0.273104  0.326747  0.959994  0.343448
319  0.009247  0.516483  0.953229  0.733671
324  0.238019  0.304172  0.070978  0.476991
330  0.161234  0.996332  0.895766  0.805775

[97 rows x 4 columns]

In [367]:
newdf.head(8)

          B         C         D         E
0  0.352351  0.357062  0.964179  0.485695
1  0.367116  0.879366  0.852277  0.843361
2  0.074232  0.702791  0.470291  0.885208
3  0.790092  0.129039  0.273185  0.012465
4  0.128046  0.552759  0.107119  0.846524
5  0.998338  0.425079  0.296949  0.632550
6  0.334803  0.237268  0.893267  0.684325
7  0.175055  0.863545  0.144510  0.070410

In [368]:
newdf.iloc[0,3]
# access the value at 0 row, and skips 3 column -> value(0,E)

np.float64(0.4856947873295141)

In [369]:
newdf.iloc[[1,2], [1,2]]

          C         D
1  0.879366  0.852277
2  0.702791  0.470291

In [370]:
newdf.head(3)

          B         C         D         E
0  0.352351  0.357062  0.964179  0.485695
1  0.367116  0.879366  0.852277  0.843361
2  0.074232  0.702791  0.470291  0.885208

In [371]:
# {newdf = newdf.drop('E', axis=1) \n newdf} ==== {newdf.drop('E', axis=1, inplace = True)}

In [372]:
newdf.drop('E', axis=1, inplace = True)

In [373]:
newdf

            B         C         D
0    0.352351  0.357062  0.964179
1    0.367116  0.879366  0.852277
2    0.074232  0.702791  0.470291
3    0.790092  0.129039  0.273185
4    0.128046  0.552759  0.107119
..        ...       ...       ...
329  0.841470  0.114174  0.916132
330  0.161234  0.996332  0.895766
331  0.882787  0.889840  0.413767
332  0.329925  0.257853  0.192152
333  0.469750  0.955389  0.225426

[334 rows x 3 columns]

In [374]:
newdf.head()

          B         C         D
0  0.352351  0.357062  0.964179
1  0.367116  0.879366  0.852277
2  0.074232  0.702791  0.470291
3  0.790092  0.129039  0.273185
4  0.128046  0.552759  0.107119

In [375]:
newdf.drop(0, axis=0, inplace=True)
newdf

            B         C         D
1    0.367116  0.879366  0.852277
2    0.074232  0.702791  0.470291
3    0.790092  0.129039  0.273185
4    0.128046  0.552759  0.107119
5    0.998338  0.425079  0.296949
..        ...       ...       ...
329  0.841470  0.114174  0.916132
330  0.161234  0.996332  0.895766
331  0.882787  0.889840  0.413767
332  0.329925  0.257853  0.192152
333  0.469750  0.955389  0.225426

[333 rows x 3 columns]

In [376]:
newdf.drop(2, axis=0, inplace=True)
newdf

            B         C         D
1    0.367116  0.879366  0.852277
3    0.790092  0.129039  0.273185
4    0.128046  0.552759  0.107119
5    0.998338  0.425079  0.296949
6    0.334803  0.237268  0.893267
..        ...       ...       ...
329  0.841470  0.114174  0.916132
330  0.161234  0.996332  0.895766
331  0.882787  0.889840  0.413767
332  0.329925  0.257853  0.192152
333  0.469750  0.955389  0.225426

[332 rows x 3 columns]

In [377]:
newdf.head()
# destructive indexing

          B         C         D
1  0.367116  0.879366  0.852277
3  0.790092  0.129039  0.273185
4  0.128046  0.552759  0.107119
5  0.998338  0.425079  0.296949
6  0.334803  0.237268  0.893267

In [378]:
newdf.reset_index()

     index         B         C         D
0        1  0.367116  0.879366  0.852277
1        3  0.790092  0.129039  0.273185
2        4  0.128046  0.552759  0.107119
3        5  0.998338  0.425079  0.296949
4        6  0.334803  0.237268  0.893267
..     ...       ...       ...       ...
327    329  0.841470  0.114174  0.916132
328    330  0.161234  0.996332  0.895766
329    331  0.882787  0.889840  0.413767
330    332  0.329925  0.257853  0.192152
331    333  0.469750  0.955389  0.225426

[332 rows x 4 columns]

In [379]:
newdf.reset_index(drop = True, inplace=True)

In [380]:
newdf

            B         C         D
0    0.367116  0.879366  0.852277
1    0.790092  0.129039  0.273185
2    0.128046  0.552759  0.107119
3    0.998338  0.425079  0.296949
4    0.334803  0.237268  0.893267
..        ...       ...       ...
327  0.841470  0.114174  0.916132
328  0.161234  0.996332  0.895766
329  0.882787  0.889840  0.413767
330  0.329925  0.257853  0.192152
331  0.469750  0.955389  0.225426

[332 rows x 3 columns]

In [381]:
newdf.head(3)

          B         C         D
0  0.367116  0.879366  0.852277
1  0.790092  0.129039  0.273185
2  0.128046  0.552759  0.107119

In [382]:
newdf['B'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
327    False
328    False
329    False
330    False
331    False
Name: B, Length: 332, dtype: bool

In [383]:
newdf['B'] = None

In [384]:
newdf['B'].isnull()

0      True
1      True
2      True
3      True
4      True
       ...
327    True
328    True
329    True
330    True
331    True
Name: B, Length: 332, dtype: bool

In [385]:
newdf['B'].notnull()

0      False
1      False
2      False
3      False
4      False
       ...
327    False
328    False
329    False
330    False
331    False
Name: B, Length: 332, dtype: bool

In [390]:
df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
                   "toy": [np.nan, 'Batmobile', 'Bullwhip'],
                   "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT]
                   })

In [391]:
df

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [392]:
df.dropna()

     name        toy       born
1  Batman  Batmobile 1940-04-25

In [393]:
df

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [394]:
df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
                   "toy": [np.nan, np.nan, np.nan],
                   "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT]
                   })

In [397]:
df

       name  toy       born
0    Alfred  NaN        NaT
1    Batman  NaN 1940-04-25
2  Catwoman  NaN        NaT

In [395]:
df.dropna(how="all", axis=1)

       name       born
0    Alfred        NaT
1    Batman 1940-04-25
2  Catwoman        NaT