In [2]:
import numpy as np
import pandas as pd

In [3]:
dict1 = {
    "name": ["kirti", "peter", "sam", "shubh"],
    "marks": [92, 93, 31, 86],
    "city": ["delhi", "calfornia", "goa", "chandigarh"]
}

In [4]:
df = pd.DataFrame(dict1)

In [5]:
print(df)

    name  marks        city
0  kirti     92       delhi
1  peter     93   calfornia
2    sam     31         goa
3  shubh     86  chandigarh

In [6]:
df.to_csv('data.csv')
df.to_csv('data_without_index.csv', index=False)

In [7]:
df.head(2)

    name  marks       city
0  kirti     92      delhi
1  peter     93  calfornia

In [8]:
df.tail(2)

    name  marks        city
2    sam     31         goa
3  shubh     86  chandigarh

In [9]:
df.describe()

           marks
count   4.000000
mean   75.500000
std    29.827281
min    31.000000
25%    72.250000
50%    89.000000
75%    92.250000
max    93.000000

In [10]:
trains = pd.read_csv('trains.csv')

In [11]:
trains

   Unnamed: 0.1  Unnamed: 0  Train No.  speed        city
0             0           0      12238     50       delhi
1             1           1      38265     28   calfornia
2             2           2      98542     31         goa
3             3           3      17662     86  chandigarh

In [12]:
trains['speed'][0] = 50

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_20296\3155761661.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  trains['speed'][0] = 50
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_20296\3155761661.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trains['speed'][0] = 50

In [13]:
trains

   Unnamed: 0.1  Unnamed: 0  Train No.  speed        city
0             0           0      12238     50       delhi
1             1           1      38265     28   calfornia
2             2           2      98542     31         goa
3             3           3      17662     86  chandigarh

In [14]:
trains.to_csv('trains.csv')

In [15]:
trains.index = ["first", "second", "third", " fourth"]
trains

         Unnamed: 0.1  Unnamed: 0  Train No.  speed        city
first               0           0      12238     50       delhi
second              1           1      38265     28   calfornia
third               2           2      98542     31         goa
 fourth             3           3      17662     86  chandigarh

In [16]:
ser = pd.Series(np.random.rand(34))
type(ser)
ser

0     0.388323
1     0.051838
2     0.583146
3     0.086538
4     0.586121
5     0.916598
6     0.121689
7     0.051718
8     0.798512
9     0.461267
10    0.818769
11    0.089675
12    0.179497
13    0.497880
14    0.498093
15    0.561258
16    0.331236
17    0.943454
18    0.444752
19    0.054364
20    0.311089
21    0.532142
22    0.395638
23    0.284696
24    0.468778
25    0.103365
26    0.440851
27    0.805651
28    0.560475
29    0.967137
30    0.699883
31    0.033547
32    0.013774
33    0.097053
dtype: float64

In [17]:
newdf = pd.DataFrame(np.random.rand(334, 5), index=np.arange(334))
print(type(newdf))
newdf

<class 'pandas.core.frame.DataFrame'>

            0         1         2         3         4
0    0.158633  0.873706  0.313766  0.212671  0.551668
1    0.998217  0.965549  0.522669  0.960172  0.393095
2    0.486428  0.160423  0.680657  0.311872  0.851683
3    0.968257  0.892022  0.755368  0.012491  0.910046
4    0.543468  0.547139  0.375742  0.357763  0.671687
..        ...       ...       ...       ...       ...
329  0.228800  0.522213  0.547394  0.575907  0.306493
330  0.660627  0.902279  0.839133  0.781086  0.427908
331  0.632545  0.923031  0.157874  0.378776  0.845349
332  0.815465  0.602731  0.952097  0.726325  0.660302
333  0.304785  0.870047  0.604152  0.326603  0.389936

[334 rows x 5 columns]

In [18]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.519280    0.531977    0.464016    0.489226    0.490985
std      0.304769    0.287981    0.278598    0.291599    0.292689
min      0.001572    0.003933    0.003316    0.012377    0.005759
25%      0.240212    0.295091    0.228582    0.265334    0.208104
50%      0.533757    0.543127    0.462357    0.457308    0.506098
75%      0.793814    0.791534    0.682787    0.726964    0.751626
max      0.999502    0.998009    0.996020    0.998135    0.995181

In [19]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [20]:
newdf[0][0] = "kirti"
newdf.head(2)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_20296\2125280267.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0] = "kirti"
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_20296\2125280267.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'kirti' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0] = "kirti"

          0         1         2         3         4
0     kirti  0.873706  0.313766  0.212671  0.551668
1  0.998217  0.965549  0.522669  0.960172  0.393095

In [21]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [22]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [23]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [24]:
newdf.to_numpy()

array([['kirti', 0.8737063485843114, 0.3137658909232247,
        0.21267112981699743, 0.5516681149458207],
       [0.9982167187038706, 0.965549056339691, 0.5226688715824924,
        0.9601718776984709, 0.3930946989753382],
       [0.4864281281554319, 0.16042288005303318, 0.6806565793786838,
        0.31187188318868253, 0.8516833940112836],
       ...,
       [0.6325445205889947, 0.9230312249123928, 0.15787357590759832,
        0.37877627659275015, 0.8453486517576984],
       [0.815464880842443, 0.6027306054910765, 0.9520970145748632,
        0.7263249729390887, 0.6603019334698597],
       [0.30478518476970606, 0.870046695685348, 0.6041524113549797,
        0.32660266122435777, 0.38993626338507037]],
      shape=(334, 5), dtype=object)

In [25]:
newdf[0][0]=0.728
newdf.head(2)

          0         1         2         3         4
0     0.728  0.873706  0.313766  0.212671  0.551668
1  0.998217  0.965549  0.522669  0.960172  0.393095

In [26]:
newdf.to_numpy()

array([[0.728, 0.8737063485843114, 0.3137658909232247,
        0.21267112981699743, 0.5516681149458207],
       [0.9982167187038706, 0.965549056339691, 0.5226688715824924,
        0.9601718776984709, 0.3930946989753382],
       [0.4864281281554319, 0.16042288005303318, 0.6806565793786838,
        0.31187188318868253, 0.8516833940112836],
       ...,
       [0.6325445205889947, 0.9230312249123928, 0.15787357590759832,
        0.37877627659275015, 0.8453486517576984],
       [0.815464880842443, 0.6027306054910765, 0.9520970145748632,
        0.7263249729390887, 0.6603019334698597],
       [0.30478518476970606, 0.870046695685348, 0.6041524113549797,
        0.32660266122435777, 0.38993626338507037]],
      shape=(334, 5), dtype=object)

In [27]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.728,0.998217,0.486428,0.968257,0.543468,0.828735,0.23604,0.119975,0.879316,0.003246,...,0.206348,0.797557,0.931844,0.843754,0.478016,0.2288,0.660627,0.632545,0.815465,0.304785
1,0.873706,0.965549,0.160423,0.892022,0.547139,0.074083,0.312197,0.782202,0.761605,0.613411,...,0.415367,0.051612,0.940008,0.265746,0.927377,0.522213,0.902279,0.923031,0.602731,0.870047
2,0.313766,0.522669,0.680657,0.755368,0.375742,0.42361,0.610723,0.49648,0.856426,0.091572,...,0.741167,0.674071,0.203793,0.737135,0.469265,0.547394,0.839133,0.157874,0.952097,0.604152
3,0.212671,0.960172,0.311872,0.012491,0.357763,0.474463,0.421219,0.066498,0.77159,0.338171,...,0.367231,0.491153,0.09178,0.452988,0.050762,0.575907,0.781086,0.378776,0.726325,0.326603
4,0.551668,0.393095,0.851683,0.910046,0.671687,0.76736,0.892703,0.203886,0.71721,0.631381,...,0.833022,0.673012,0.154497,0.050529,0.512039,0.306493,0.427908,0.845349,0.660302,0.389936

In [28]:
newdf.head()

          0         1         2         3         4
0     0.728  0.873706  0.313766  0.212671  0.551668
1  0.998217  0.965549  0.522669  0.960172  0.393095
2  0.486428  0.160423  0.680657  0.311872  0.851683
3  0.968257  0.892022  0.755368  0.012491  0.910046
4  0.543468  0.547139  0.375742  0.357763  0.671687

In [29]:
newdf.sort_index(axis = 1, ascending=False)
# across coloumns

            4         3         2         1         0
0    0.551668  0.212671  0.313766  0.873706     0.728
1    0.393095  0.960172  0.522669  0.965549  0.998217
2    0.851683  0.311872  0.680657  0.160423  0.486428
3    0.910046  0.012491  0.755368  0.892022  0.968257
4    0.671687  0.357763  0.375742  0.547139  0.543468
..        ...       ...       ...       ...       ...
329  0.306493  0.575907  0.547394  0.522213    0.2288
330  0.427908  0.781086  0.839133  0.902279  0.660627
331  0.845349  0.378776  0.157874  0.923031  0.632545
332  0.660302  0.726325  0.952097  0.602731  0.815465
333  0.389936  0.326603  0.604152  0.870047  0.304785

[334 rows x 5 columns]

In [30]:
newdf.sort_index(axis=0, ascending=False)
# across rows

            0         1         2         3         4
333  0.304785  0.870047  0.604152  0.326603  0.389936
332  0.815465  0.602731  0.952097  0.726325  0.660302
331  0.632545  0.923031  0.157874  0.378776  0.845349
330  0.660627  0.902279  0.839133  0.781086  0.427908
329    0.2288  0.522213  0.547394  0.575907  0.306493
..        ...       ...       ...       ...       ...
4    0.543468  0.547139  0.375742  0.357763  0.671687
3    0.968257  0.892022  0.755368  0.012491  0.910046
2    0.486428  0.160423  0.680657  0.311872  0.851683
1    0.998217  0.965549  0.522669  0.960172  0.393095
0       0.728  0.873706  0.313766  0.212671  0.551668

[334 rows x 5 columns]

In [31]:
type(newdf[0])

pandas.core.series.Series

In [32]:
newdf2 = newdf