In [406]:
import numpy as np
import pandas as pd

In [407]:
dict1 = {
    "name": ["kirti", "peter", "sam", "shubh"],
    "marks": [92, 93, 31, 86],
    "city": ["delhi", "calfornia", "goa", "chandigarh"]
}

In [408]:
df = pd.DataFrame(dict1)

In [409]:
print(df)

    name  marks        city
0  kirti     92       delhi
1  peter     93   calfornia
2    sam     31         goa
3  shubh     86  chandigarh

In [410]:
df.to_csv('data.csv')
df.to_csv('data_without_index.csv', index=False)

In [411]:
df.head(2)

    name  marks       city
0  kirti     92      delhi
1  peter     93  calfornia

In [412]:
df.tail(2)

    name  marks        city
2    sam     31         goa
3  shubh     86  chandigarh

In [413]:
df.describe()

           marks
count   4.000000
mean   75.500000
std    29.827281
min    31.000000
25%    72.250000
50%    89.000000
75%    92.250000
max    93.000000

In [414]:
trains = pd.read_csv('trains.csv')

In [415]:
trains

,Unnamed: 0.9,Unnamed: 0.8,Unnamed: 0.7,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Train No.,speed,city
0,0,0,0,0,0,0,0,0,0,0,12238,50,delhi
1,1,1,1,1,1,1,1,1,1,1,38265,28,calfornia
2,2,2,2,2,2,2,2,2,2,2,98542,31,goa
3,3,3,3,3,3,3,3,3,3,3,17662,86,chandigarh

In [416]:
trains['speed'][0] = 50

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\3155761661.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  trains['speed'][0] = 50
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\3155761661.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trains['speed'][0] = 50

In [417]:
trains

,Unnamed: 0.9,Unnamed: 0.8,Unnamed: 0.7,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Train No.,speed,city
0,0,0,0,0,0,0,0,0,0,0,12238,50,delhi
1,1,1,1,1,1,1,1,1,1,1,38265,28,calfornia
2,2,2,2,2,2,2,2,2,2,2,98542,31,goa
3,3,3,3,3,3,3,3,3,3,3,17662,86,chandigarh

In [418]:
trains.to_csv('trains.csv')

In [419]:
trains.index = ["first", "second", "third", " fourth"]
trains

,Unnamed: 0.9,Unnamed: 0.8,Unnamed: 0.7,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Train No.,speed,city
first,0,0,0,0,0,0,0,0,0,0,12238,50,delhi
second,1,1,1,1,1,1,1,1,1,1,38265,28,calfornia
third,2,2,2,2,2,2,2,2,2,2,98542,31,goa
fourth,3,3,3,3,3,3,3,3,3,3,17662,86,chandigarh

In [420]:
ser = pd.Series(np.random.rand(34))
type(ser)
ser

0     0.567470
1     0.484823
2     0.335839
3     0.724016
4     0.298076
5     0.299360
6     0.767462
7     0.780910
8     0.657363
9     0.969277
10    0.943390
11    0.292837
12    0.725079
13    0.537216
14    0.276925
15    0.663908
16    0.819083
17    0.851316
18    0.114354
19    0.176703
20    0.673520
21    0.608056
22    0.753784
23    0.228749
24    0.342694
25    0.504167
26    0.706121
27    0.519222
28    0.696316
29    0.031783
30    0.823619
31    0.595244
32    0.043165
33    0.970570
dtype: float64

In [421]:
newdf = pd.DataFrame(np.random.rand(334, 5), index=np.arange(334))
print(type(newdf))
newdf

<class 'pandas.core.frame.DataFrame'>

            0         1         2         3         4
0    0.609669  0.652678  0.287878  0.049915  0.101483
1    0.338181  0.780564  0.256611  0.432597  0.966961
2    0.693541  0.580211  0.833328  0.286967  0.610364
3    0.167562  0.078150  0.220118  0.414310  0.867598
4    0.297074  0.682258  0.343649  0.977964  0.913302
..        ...       ...       ...       ...       ...
329  0.342789  0.590236  0.260199  0.748313  0.162145
330  0.957719  0.291543  0.237438  0.010158  0.463144
331  0.109601  0.868289  0.523502  0.061882  0.797225
332  0.152903  0.187262  0.555669  0.076253  0.726373
333  0.306684  0.808499  0.982985  0.445830  0.223770

[334 rows x 5 columns]

In [422]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.487607    0.469091    0.499473    0.495931    0.495280
std      0.281850    0.286704    0.295380    0.297089    0.284704
min      0.001661    0.004647    0.001563    0.005676    0.001909
25%      0.252784    0.216277    0.242853    0.217347    0.251957
50%      0.505226    0.468725    0.488402    0.506384    0.489209
75%      0.698658    0.716886    0.767201    0.758553    0.742408
max      0.999506    0.998900    0.995672    0.992931    0.999617

In [423]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [424]:
newdf[0][0] = "kirti"
newdf.head(2)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\2125280267.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0] = "kirti"
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\2125280267.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'kirti' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0] = "kirti"

          0         1         2         3         4
0     kirti  0.652678  0.287878  0.049915  0.101483
1  0.338181  0.780564  0.256611  0.432597  0.966961

In [425]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [426]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [427]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [428]:
newdf.to_numpy()

array([['kirti', 0.6526777031325736, 0.28787848023398943,
        0.04991469264077075, 0.10148256943906953],
       [0.33818105753090444, 0.7805643695073156, 0.2566109286424292,
        0.4325967952763923, 0.9669613642719526],
       [0.6935407624124823, 0.5802113811437035, 0.8333279287558056,
        0.28696727629367036, 0.6103641715790126],
       ...,
       [0.10960112813511103, 0.8682893466701737, 0.5235015170952968,
        0.06188222987549785, 0.7972246770945359],
       [0.15290296926065927, 0.18726249038474085, 0.5556685354288454,
        0.07625280208053209, 0.7263727960185815],
       [0.3066840264374261, 0.808498786604914, 0.9829846594936232,
        0.4458299989751252, 0.22376952290619911]],
      shape=(334, 5), dtype=object)

In [429]:
newdf[0][0]=0.728
newdf.head(2)

          0         1         2         3         4
0     0.728  0.652678  0.287878  0.049915  0.101483
1  0.338181  0.780564  0.256611  0.432597  0.966961

In [430]:
newdf.to_numpy()

array([[0.728, 0.6526777031325736, 0.28787848023398943,
        0.04991469264077075, 0.10148256943906953],
       [0.33818105753090444, 0.7805643695073156, 0.2566109286424292,
        0.4325967952763923, 0.9669613642719526],
       [0.6935407624124823, 0.5802113811437035, 0.8333279287558056,
        0.28696727629367036, 0.6103641715790126],
       ...,
       [0.10960112813511103, 0.8682893466701737, 0.5235015170952968,
        0.06188222987549785, 0.7972246770945359],
       [0.15290296926065927, 0.18726249038474085, 0.5556685354288454,
        0.07625280208053209, 0.7263727960185815],
       [0.3066840264374261, 0.808498786604914, 0.9829846594936232,
        0.4458299989751252, 0.22376952290619911]],
      shape=(334, 5), dtype=object)

In [431]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.728,0.338181,0.693541,0.167562,0.297074,0.645249,0.861721,0.562443,0.272616,0.538173,...,0.01747,0.5391,0.327544,0.826092,0.366336,0.342789,0.957719,0.109601,0.152903,0.306684
1,0.652678,0.780564,0.580211,0.07815,0.682258,0.843946,0.480225,0.085146,0.748286,0.675367,...,0.370366,0.804199,0.71729,0.825186,0.519384,0.590236,0.291543,0.868289,0.187262,0.808499
2,0.287878,0.256611,0.833328,0.220118,0.343649,0.520505,0.149787,0.813084,0.861238,0.357028,...,0.460833,0.952977,0.767361,0.541047,0.674615,0.260199,0.237438,0.523502,0.555669,0.982985
3,0.049915,0.432597,0.286967,0.41431,0.977964,0.76939,0.394691,0.057366,0.844763,0.78888,...,0.937663,0.147778,0.650708,0.960842,0.082854,0.748313,0.010158,0.061882,0.076253,0.44583
4,0.101483,0.966961,0.610364,0.867598,0.913302,0.324309,0.312346,0.17357,0.978955,0.120023,...,0.600215,0.630403,0.805932,0.779453,0.31852,0.162145,0.463144,0.797225,0.726373,0.22377

In [432]:
newdf.head()

          0         1         2         3         4
0     0.728  0.652678  0.287878  0.049915  0.101483
1  0.338181  0.780564  0.256611  0.432597  0.966961
2  0.693541  0.580211  0.833328  0.286967  0.610364
3  0.167562  0.078150  0.220118  0.414310  0.867598
4  0.297074  0.682258  0.343649  0.977964  0.913302

In [433]:
newdf.sort_index(axis = 1, ascending=False)
# across coloumns

            4         3         2         1         0
0    0.101483  0.049915  0.287878  0.652678     0.728
1    0.966961  0.432597  0.256611  0.780564  0.338181
2    0.610364  0.286967  0.833328  0.580211  0.693541
3    0.867598  0.414310  0.220118  0.078150  0.167562
4    0.913302  0.977964  0.343649  0.682258  0.297074
..        ...       ...       ...       ...       ...
329  0.162145  0.748313  0.260199  0.590236  0.342789
330  0.463144  0.010158  0.237438  0.291543  0.957719
331  0.797225  0.061882  0.523502  0.868289  0.109601
332  0.726373  0.076253  0.555669  0.187262  0.152903
333  0.223770  0.445830  0.982985  0.808499  0.306684

[334 rows x 5 columns]

In [434]:
newdf.sort_index(axis=0, ascending=False)
# across rows

            0         1         2         3         4
333  0.306684  0.808499  0.982985  0.445830  0.223770
332  0.152903  0.187262  0.555669  0.076253  0.726373
331  0.109601  0.868289  0.523502  0.061882  0.797225
330  0.957719  0.291543  0.237438  0.010158  0.463144
329  0.342789  0.590236  0.260199  0.748313  0.162145
..        ...       ...       ...       ...       ...
4    0.297074  0.682258  0.343649  0.977964  0.913302
3    0.167562  0.078150  0.220118  0.414310  0.867598
2    0.693541  0.580211  0.833328  0.286967  0.610364
1    0.338181  0.780564  0.256611  0.432597  0.966961
0       0.728  0.652678  0.287878  0.049915  0.101483

[334 rows x 5 columns]

In [435]:
type(newdf[0])

pandas.core.series.Series

In [436]:
newdf2 = newdf
# here newdf2 is the view (pointing to newdf)

In [437]:
newdf2[0][0] = 7283

In [438]:
newdf

            0         1         2         3         4
0        7283  0.652678  0.287878  0.049915  0.101483
1    0.338181  0.780564  0.256611  0.432597  0.966961
2    0.693541  0.580211  0.833328  0.286967  0.610364
3    0.167562  0.078150  0.220118  0.414310  0.867598
4    0.297074  0.682258  0.343649  0.977964  0.913302
..        ...       ...       ...       ...       ...
329  0.342789  0.590236  0.260199  0.748313  0.162145
330  0.957719  0.291543  0.237438  0.010158  0.463144
331  0.109601  0.868289  0.523502  0.061882  0.797225
332  0.152903  0.187262  0.555669  0.076253  0.726373
333  0.306684  0.808499  0.982985  0.445830  0.223770

[334 rows x 5 columns]

In [439]:
newdf3 = newdf.copy()
newdf3[0][0] = 82
newdf

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\575451395.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf3[0][0] = 82
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\575451395.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf3[0][0] = 82

            0         1         2         3         4
0        7283  0.652678  0.287878  0.049915  0.101483
1    0.338181  0.780564  0.256611  0.432597  0.966961
2    0.693541  0.580211  0.833328  0.286967  0.610364
3    0.167562  0.078150  0.220118  0.414310  0.867598
4    0.297074  0.682258  0.343649  0.977964  0.913302
..        ...       ...       ...       ...       ...
329  0.342789  0.590236  0.260199  0.748313  0.162145
330  0.957719  0.291543  0.237438  0.010158  0.463144
331  0.109601  0.868289  0.523502  0.061882  0.797225
332  0.152903  0.187262  0.555669  0.076253  0.726373
333  0.306684  0.808499  0.982985  0.445830  0.223770

[334 rows x 5 columns]

In [440]:
newdf

            0         1         2         3         4
0        7283  0.652678  0.287878  0.049915  0.101483
1    0.338181  0.780564  0.256611  0.432597  0.966961
2    0.693541  0.580211  0.833328  0.286967  0.610364
3    0.167562  0.078150  0.220118  0.414310  0.867598
4    0.297074  0.682258  0.343649  0.977964  0.913302
..        ...       ...       ...       ...       ...
329  0.342789  0.590236  0.260199  0.748313  0.162145
330  0.957719  0.291543  0.237438  0.010158  0.463144
331  0.109601  0.868289  0.523502  0.061882  0.797225
332  0.152903  0.187262  0.555669  0.076253  0.726373
333  0.306684  0.808499  0.982985  0.445830  0.223770

[334 rows x 5 columns]

In [441]:
newdf.loc[0,0] = 26
# helps in accessing the values by specifying the position

In [442]:
newdf

            0         1         2         3         4
0          26  0.652678  0.287878  0.049915  0.101483
1    0.338181  0.780564  0.256611  0.432597  0.966961
2    0.693541  0.580211  0.833328  0.286967  0.610364
3    0.167562  0.078150  0.220118  0.414310  0.867598
4    0.297074  0.682258  0.343649  0.977964  0.913302
..        ...       ...       ...       ...       ...
329  0.342789  0.590236  0.260199  0.748313  0.162145
330  0.957719  0.291543  0.237438  0.010158  0.463144
331  0.109601  0.868289  0.523502  0.061882  0.797225
332  0.152903  0.187262  0.555669  0.076253  0.726373
333  0.306684  0.808499  0.982985  0.445830  0.223770

[334 rows x 5 columns]

In [443]:
newdf.columns = list("ABCDE")

In [444]:
newdf

            A         B         C         D         E
0          26  0.652678  0.287878  0.049915  0.101483
1    0.338181  0.780564  0.256611  0.432597  0.966961
2    0.693541  0.580211  0.833328  0.286967  0.610364
3    0.167562  0.078150  0.220118  0.414310  0.867598
4    0.297074  0.682258  0.343649  0.977964  0.913302
..        ...       ...       ...       ...       ...
329  0.342789  0.590236  0.260199  0.748313  0.162145
330  0.957719  0.291543  0.237438  0.010158  0.463144
331  0.109601  0.868289  0.523502  0.061882  0.797225
332  0.152903  0.187262  0.555669  0.076253  0.726373
333  0.306684  0.808499  0.982985  0.445830  0.223770

[334 rows x 5 columns]

In [445]:
newdf = newdf.drop('A', axis=1)  
# changes column
newdf

            B         C         D         E
0    0.652678  0.287878  0.049915  0.101483
1    0.780564  0.256611  0.432597  0.966961
2    0.580211  0.833328  0.286967  0.610364
3    0.078150  0.220118  0.414310  0.867598
4    0.682258  0.343649  0.977964  0.913302
..        ...       ...       ...       ...
329  0.590236  0.260199  0.748313  0.162145
330  0.291543  0.237438  0.010158  0.463144
331  0.868289  0.523502  0.061882  0.797225
332  0.187262  0.555669  0.076253  0.726373
333  0.808499  0.982985  0.445830  0.223770

[334 rows x 4 columns]

In [446]:
newdf.loc[[1,2], ['C','D']]

          C         D
1  0.256611  0.432597
2  0.833328  0.286967

In [447]:
newdf.head()

          B         C         D         E
0  0.652678  0.287878  0.049915  0.101483
1  0.780564  0.256611  0.432597  0.966961
2  0.580211  0.833328  0.286967  0.610364
3  0.078150  0.220118  0.414310  0.867598
4  0.682258  0.343649  0.977964  0.913302

In [448]:
newdf.loc[[1,2],:]

          B         C         D         E
1  0.780564  0.256611  0.432597  0.966961
2  0.580211  0.833328  0.286967  0.610364

In [449]:
newdf.loc[(newdf['B']<0.3)]

            B         C         D         E
3    0.078150  0.220118  0.414310  0.867598
7    0.085146  0.813084  0.057366  0.173570
11   0.027782  0.818876  0.819140  0.086078
17   0.149470  0.559092  0.430658  0.580062
19   0.133305  0.429947  0.115352  0.884349
..        ...       ...       ...       ...
316  0.186235  0.195538  0.580914  0.292938
319  0.280655  0.776611  0.561571  0.083639
321  0.286053  0.467228  0.804959  0.940528
330  0.291543  0.237438  0.010158  0.463144
332  0.187262  0.555669  0.076253  0.726373

[114 rows x 4 columns]

In [450]:
newdf.loc[(newdf['B']<0.3) & (newdf['C']>0.1)]

            B         C         D         E
3    0.078150  0.220118  0.414310  0.867598
7    0.085146  0.813084  0.057366  0.173570
11   0.027782  0.818876  0.819140  0.086078
17   0.149470  0.559092  0.430658  0.580062
19   0.133305  0.429947  0.115352  0.884349
..        ...       ...       ...       ...
316  0.186235  0.195538  0.580914  0.292938
319  0.280655  0.776611  0.561571  0.083639
321  0.286053  0.467228  0.804959  0.940528
330  0.291543  0.237438  0.010158  0.463144
332  0.187262  0.555669  0.076253  0.726373

[103 rows x 4 columns]

In [451]:
newdf.head(8)

          B         C         D         E
0  0.652678  0.287878  0.049915  0.101483
1  0.780564  0.256611  0.432597  0.966961
2  0.580211  0.833328  0.286967  0.610364
3  0.078150  0.220118  0.414310  0.867598
4  0.682258  0.343649  0.977964  0.913302
5  0.843946  0.520505  0.769390  0.324309
6  0.480225  0.149787  0.394691  0.312346
7  0.085146  0.813084  0.057366  0.173570

In [452]:
newdf.iloc[0,3]
# access the value at 0 row, and skips 3 column -> value(0,E)

np.float64(0.10148256943906953)

In [453]:
newdf.iloc[[1,2], [1,2]]

          C         D
1  0.256611  0.432597
2  0.833328  0.286967

In [454]:
newdf.head(3)

          B         C         D         E
0  0.652678  0.287878  0.049915  0.101483
1  0.780564  0.256611  0.432597  0.966961
2  0.580211  0.833328  0.286967  0.610364

In [455]:
# {newdf = newdf.drop('E', axis=1) \n newdf} ==== {newdf.drop('E', axis=1, inplace = True)}

In [456]:
newdf.drop('E', axis=1, inplace = True)

In [457]:
newdf

            B         C         D
0    0.652678  0.287878  0.049915
1    0.780564  0.256611  0.432597
2    0.580211  0.833328  0.286967
3    0.078150  0.220118  0.414310
4    0.682258  0.343649  0.977964
..        ...       ...       ...
329  0.590236  0.260199  0.748313
330  0.291543  0.237438  0.010158
331  0.868289  0.523502  0.061882
332  0.187262  0.555669  0.076253
333  0.808499  0.982985  0.445830

[334 rows x 3 columns]

In [458]:
newdf.head()

          B         C         D
0  0.652678  0.287878  0.049915
1  0.780564  0.256611  0.432597
2  0.580211  0.833328  0.286967
3  0.078150  0.220118  0.414310
4  0.682258  0.343649  0.977964

In [459]:
newdf.drop(0, axis=0, inplace=True)
newdf

            B         C         D
1    0.780564  0.256611  0.432597
2    0.580211  0.833328  0.286967
3    0.078150  0.220118  0.414310
4    0.682258  0.343649  0.977964
5    0.843946  0.520505  0.769390
..        ...       ...       ...
329  0.590236  0.260199  0.748313
330  0.291543  0.237438  0.010158
331  0.868289  0.523502  0.061882
332  0.187262  0.555669  0.076253
333  0.808499  0.982985  0.445830

[333 rows x 3 columns]

In [460]:
newdf.drop(2, axis=0, inplace=True)
newdf

            B         C         D
1    0.780564  0.256611  0.432597
3    0.078150  0.220118  0.414310
4    0.682258  0.343649  0.977964
5    0.843946  0.520505  0.769390
6    0.480225  0.149787  0.394691
..        ...       ...       ...
329  0.590236  0.260199  0.748313
330  0.291543  0.237438  0.010158
331  0.868289  0.523502  0.061882
332  0.187262  0.555669  0.076253
333  0.808499  0.982985  0.445830

[332 rows x 3 columns]

In [461]:
newdf.head()
# destructive indexing

          B         C         D
1  0.780564  0.256611  0.432597
3  0.078150  0.220118  0.414310
4  0.682258  0.343649  0.977964
5  0.843946  0.520505  0.769390
6  0.480225  0.149787  0.394691

In [462]:
newdf.reset_index()

     index         B         C         D
0        1  0.780564  0.256611  0.432597
1        3  0.078150  0.220118  0.414310
2        4  0.682258  0.343649  0.977964
3        5  0.843946  0.520505  0.769390
4        6  0.480225  0.149787  0.394691
..     ...       ...       ...       ...
327    329  0.590236  0.260199  0.748313
328    330  0.291543  0.237438  0.010158
329    331  0.868289  0.523502  0.061882
330    332  0.187262  0.555669  0.076253
331    333  0.808499  0.982985  0.445830

[332 rows x 4 columns]

In [463]:
newdf.reset_index(drop = True, inplace=True)

In [464]:
newdf

            B         C         D
0    0.780564  0.256611  0.432597
1    0.078150  0.220118  0.414310
2    0.682258  0.343649  0.977964
3    0.843946  0.520505  0.769390
4    0.480225  0.149787  0.394691
..        ...       ...       ...
327  0.590236  0.260199  0.748313
328  0.291543  0.237438  0.010158
329  0.868289  0.523502  0.061882
330  0.187262  0.555669  0.076253
331  0.808499  0.982985  0.445830

[332 rows x 3 columns]

In [465]:
newdf.head(3)

          B         C         D
0  0.780564  0.256611  0.432597
1  0.078150  0.220118  0.414310
2  0.682258  0.343649  0.977964

In [466]:
newdf['B'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
327    False
328    False
329    False
330    False
331    False
Name: B, Length: 332, dtype: bool

In [467]:
newdf['B'] = None

In [468]:
newdf['B'].isnull()

0      True
1      True
2      True
3      True
4      True
       ...
327    True
328    True
329    True
330    True
331    True
Name: B, Length: 332, dtype: bool

In [469]:
newdf['B'].notnull()

0      False
1      False
2      False
3      False
4      False
       ...
327    False
328    False
329    False
330    False
331    False
Name: B, Length: 332, dtype: bool

In [470]:
df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
                   "toy": [np.nan, 'Batmobile', 'Bullwhip'],
                   "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT]
                   })

In [471]:
df

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [472]:
df.dropna()

     name        toy       born
1  Batman  Batmobile 1940-04-25

In [473]:
df

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [474]:
df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
                   "toy": [np.nan, np.nan, np.nan],
                   "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT]
                   })

In [475]:
df

       name  toy       born
0    Alfred  NaN        NaT
1    Batman  NaN 1940-04-25
2  Catwoman  NaN        NaT

In [476]:
df.dropna(how="all", axis=1)

       name       born
0    Alfred        NaT
1    Batman 1940-04-25
2  Catwoman        NaT

In [477]:
df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Alfred'],
                   "toy": [np.nan, np.nan, np.nan],
                   "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT]
                   })

In [478]:
df

     name  toy       born
0  Alfred  NaN        NaT
1  Batman  NaN 1940-04-25
2  Alfred  NaN        NaT

In [481]:
df.drop_duplicates(subset=['name'], inplace=True)

In [482]:
df

     name  toy       born
0  Alfred  NaN        NaT
1  Batman  NaN 1940-04-25