In [253]:
import numpy as np
import pandas as pd

In [254]:
dict1 = {
    "name": ["kirti", "peter", "sam", "shubh"],
    "marks": [92, 93, 31, 86],
    "city": ["delhi", "calfornia", "goa", "chandigarh"]
}

In [255]:
df = pd.DataFrame(dict1)

In [256]:
print(df)

    name  marks        city
0  kirti     92       delhi
1  peter     93   calfornia
2    sam     31         goa
3  shubh     86  chandigarh

In [257]:
df.to_csv('data.csv')
df.to_csv('data_without_index.csv', index=False)

In [258]:
df.head(2)

    name  marks       city
0  kirti     92      delhi
1  peter     93  calfornia

In [259]:
df.tail(2)

    name  marks        city
2    sam     31         goa
3  shubh     86  chandigarh

In [260]:
df.describe()

           marks
count   4.000000
mean   75.500000
std    29.827281
min    31.000000
25%    72.250000
50%    89.000000
75%    92.250000
max    93.000000

In [261]:
trains = pd.read_csv('trains.csv')

In [262]:
trains

,Unnamed: 0.7,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Train No.,speed,city
0,0,0,0,0,0,0,0,0,12238,50,delhi
1,1,1,1,1,1,1,1,1,38265,28,calfornia
2,2,2,2,2,2,2,2,2,98542,31,goa
3,3,3,3,3,3,3,3,3,17662,86,chandigarh

In [263]:
trains['speed'][0] = 50

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\3155761661.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  trains['speed'][0] = 50
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\3155761661.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trains['speed'][0] = 50

In [264]:
trains

,Unnamed: 0.7,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Train No.,speed,city
0,0,0,0,0,0,0,0,0,12238,50,delhi
1,1,1,1,1,1,1,1,1,38265,28,calfornia
2,2,2,2,2,2,2,2,2,98542,31,goa
3,3,3,3,3,3,3,3,3,17662,86,chandigarh

In [265]:
trains.to_csv('trains.csv')

In [266]:
trains.index = ["first", "second", "third", " fourth"]
trains

,Unnamed: 0.7,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Train No.,speed,city
first,0,0,0,0,0,0,0,0,12238,50,delhi
second,1,1,1,1,1,1,1,1,38265,28,calfornia
third,2,2,2,2,2,2,2,2,98542,31,goa
fourth,3,3,3,3,3,3,3,3,17662,86,chandigarh

In [267]:
ser = pd.Series(np.random.rand(34))
type(ser)
ser

0     0.000171
1     0.100992
2     0.110872
3     0.007855
4     0.205263
5     0.073150
6     0.527222
7     0.733584
8     0.201571
9     0.748936
10    0.193561
11    0.196993
12    0.580266
13    0.923318
14    0.552533
15    0.510194
16    0.646803
17    0.688327
18    0.340034
19    0.722509
20    0.559542
21    0.962253
22    0.754302
23    0.426106
24    0.643273
25    0.971133
26    0.897436
27    0.738037
28    0.450370
29    0.068420
30    0.615525
31    0.502882
32    0.656830
33    0.307770
dtype: float64

In [268]:
newdf = pd.DataFrame(np.random.rand(334, 5), index=np.arange(334))
print(type(newdf))
newdf

<class 'pandas.core.frame.DataFrame'>

            0         1         2         3         4
0    0.089218  0.520174  0.690723  0.207875  0.544086
1    0.931627  0.626650  0.013876  0.673938  0.733962
2    0.049810  0.048008  0.249437  0.831439  0.601342
3    0.797763  0.894796  0.529755  0.704252  0.680406
4    0.011163  0.227519  0.645605  0.258580  0.426857
..        ...       ...       ...       ...       ...
329  0.604284  0.870458  0.643308  0.172701  0.756001
330  0.208461  0.917903  0.915896  0.643644  0.194964
331  0.462388  0.555937  0.916902  0.626838  0.447284
332  0.448996  0.235560  0.620477  0.848534  0.296294
333  0.370733  0.662997  0.179534  0.244978  0.981081

[334 rows x 5 columns]

In [269]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.501334    0.486229    0.494469    0.512047    0.493043
std      0.289740    0.295281    0.291276    0.294886    0.302126
min      0.008782    0.004276    0.003195    0.000188    0.003270
25%      0.244601    0.228413    0.243281    0.248235    0.234143
50%      0.494266    0.460180    0.490218    0.529420    0.471289
75%      0.765955    0.745336    0.733070    0.773727    0.761706
max      0.998745    0.998511    0.992435    0.999849    0.999984

In [270]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [271]:
newdf[0][0] = "kirti"
newdf.head(2)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\2125280267.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0] = "kirti"
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\2125280267.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'kirti' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0] = "kirti"

          0         1         2         3         4
0     kirti  0.520174  0.690723  0.207875  0.544086
1  0.931627  0.626650  0.013876  0.673938  0.733962

In [272]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [273]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [274]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [275]:
newdf.to_numpy()

array([['kirti', 0.5201740727514571, 0.6907234286226928,
        0.20787483271382523, 0.5440856406624633],
       [0.9316274262994442, 0.6266501334282192, 0.013875790838134616,
        0.6739379631395481, 0.7339616819414863],
       [0.049810196175890664, 0.04800831822434626, 0.24943723868601353,
        0.8314388410137883, 0.6013418382407986],
       ...,
       [0.4623880444301056, 0.5559371699768811, 0.9169016379480545,
        0.6268379928044395, 0.447283606859887],
       [0.4489963156879956, 0.23556006465411128, 0.6204771788466273,
        0.8485341473934669, 0.29629385723876756],
       [0.37073267267457755, 0.662997490881528, 0.17953350595117723,
        0.24497779668612452, 0.9810806615906887]],
      shape=(334, 5), dtype=object)

In [276]:
newdf[0][0]=0.728
newdf.head(2)

          0         1         2         3         4
0     0.728  0.520174  0.690723  0.207875  0.544086
1  0.931627  0.626650  0.013876  0.673938  0.733962

In [277]:
newdf.to_numpy()

array([[0.728, 0.5201740727514571, 0.6907234286226928,
        0.20787483271382523, 0.5440856406624633],
       [0.9316274262994442, 0.6266501334282192, 0.013875790838134616,
        0.6739379631395481, 0.7339616819414863],
       [0.049810196175890664, 0.04800831822434626, 0.24943723868601353,
        0.8314388410137883, 0.6013418382407986],
       ...,
       [0.4623880444301056, 0.5559371699768811, 0.9169016379480545,
        0.6268379928044395, 0.447283606859887],
       [0.4489963156879956, 0.23556006465411128, 0.6204771788466273,
        0.8485341473934669, 0.29629385723876756],
       [0.37073267267457755, 0.662997490881528, 0.17953350595117723,
        0.24497779668612452, 0.9810806615906887]],
      shape=(334, 5), dtype=object)

In [278]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.728,0.931627,0.04981,0.797763,0.011163,0.328411,0.9065,0.853834,0.227015,0.627065,...,0.930797,0.401033,0.974152,0.544318,0.045711,0.604284,0.208461,0.462388,0.448996,0.370733
1,0.520174,0.62665,0.048008,0.894796,0.227519,0.118182,0.51859,0.651064,0.509042,0.867819,...,0.301943,0.503543,0.127671,0.171687,0.670519,0.870458,0.917903,0.555937,0.23556,0.662997
2,0.690723,0.013876,0.249437,0.529755,0.645605,0.612987,0.349785,0.011323,0.499813,0.300833,...,0.911805,0.414813,0.036935,0.15427,0.987439,0.643308,0.915896,0.916902,0.620477,0.179534
3,0.207875,0.673938,0.831439,0.704252,0.25858,0.93858,0.439394,0.561389,0.904892,0.999043,...,0.578053,0.709496,0.290364,0.393523,0.05122,0.172701,0.643644,0.626838,0.848534,0.244978
4,0.544086,0.733962,0.601342,0.680406,0.426857,0.629769,0.75654,0.403643,0.943888,0.269165,...,0.27764,0.152693,0.473569,0.609686,0.837886,0.756001,0.194964,0.447284,0.296294,0.981081

In [279]:
newdf.head()

          0         1         2         3         4
0     0.728  0.520174  0.690723  0.207875  0.544086
1  0.931627  0.626650  0.013876  0.673938  0.733962
2   0.04981  0.048008  0.249437  0.831439  0.601342
3  0.797763  0.894796  0.529755  0.704252  0.680406
4  0.011163  0.227519  0.645605  0.258580  0.426857

In [280]:
newdf.sort_index(axis = 1, ascending=False)
# across coloumns

            4         3         2         1         0
0    0.544086  0.207875  0.690723  0.520174     0.728
1    0.733962  0.673938  0.013876  0.626650  0.931627
2    0.601342  0.831439  0.249437  0.048008   0.04981
3    0.680406  0.704252  0.529755  0.894796  0.797763
4    0.426857  0.258580  0.645605  0.227519  0.011163
..        ...       ...       ...       ...       ...
329  0.756001  0.172701  0.643308  0.870458  0.604284
330  0.194964  0.643644  0.915896  0.917903  0.208461
331  0.447284  0.626838  0.916902  0.555937  0.462388
332  0.296294  0.848534  0.620477  0.235560  0.448996
333  0.981081  0.244978  0.179534  0.662997  0.370733

[334 rows x 5 columns]

In [281]:
newdf.sort_index(axis=0, ascending=False)
# across rows

            0         1         2         3         4
333  0.370733  0.662997  0.179534  0.244978  0.981081
332  0.448996  0.235560  0.620477  0.848534  0.296294
331  0.462388  0.555937  0.916902  0.626838  0.447284
330  0.208461  0.917903  0.915896  0.643644  0.194964
329  0.604284  0.870458  0.643308  0.172701  0.756001
..        ...       ...       ...       ...       ...
4    0.011163  0.227519  0.645605  0.258580  0.426857
3    0.797763  0.894796  0.529755  0.704252  0.680406
2     0.04981  0.048008  0.249437  0.831439  0.601342
1    0.931627  0.626650  0.013876  0.673938  0.733962
0       0.728  0.520174  0.690723  0.207875  0.544086

[334 rows x 5 columns]

In [282]:
type(newdf[0])

pandas.core.series.Series

In [283]:
newdf2 = newdf
# here newdf2 is the view (pointing to newdf)

In [284]:
newdf2[0][0] = 7283

In [285]:
newdf

            0         1         2         3         4
0        7283  0.520174  0.690723  0.207875  0.544086
1    0.931627  0.626650  0.013876  0.673938  0.733962
2     0.04981  0.048008  0.249437  0.831439  0.601342
3    0.797763  0.894796  0.529755  0.704252  0.680406
4    0.011163  0.227519  0.645605  0.258580  0.426857
..        ...       ...       ...       ...       ...
329  0.604284  0.870458  0.643308  0.172701  0.756001
330  0.208461  0.917903  0.915896  0.643644  0.194964
331  0.462388  0.555937  0.916902  0.626838  0.447284
332  0.448996  0.235560  0.620477  0.848534  0.296294
333  0.370733  0.662997  0.179534  0.244978  0.981081

[334 rows x 5 columns]

In [286]:
newdf3 = newdf.copy()
newdf3[0][0] = 82
newdf

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\575451395.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf3[0][0] = 82
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19068\575451395.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf3[0][0] = 82

            0         1         2         3         4
0        7283  0.520174  0.690723  0.207875  0.544086
1    0.931627  0.626650  0.013876  0.673938  0.733962
2     0.04981  0.048008  0.249437  0.831439  0.601342
3    0.797763  0.894796  0.529755  0.704252  0.680406
4    0.011163  0.227519  0.645605  0.258580  0.426857
..        ...       ...       ...       ...       ...
329  0.604284  0.870458  0.643308  0.172701  0.756001
330  0.208461  0.917903  0.915896  0.643644  0.194964
331  0.462388  0.555937  0.916902  0.626838  0.447284
332  0.448996  0.235560  0.620477  0.848534  0.296294
333  0.370733  0.662997  0.179534  0.244978  0.981081

[334 rows x 5 columns]

In [287]:
newdf

            0         1         2         3         4
0        7283  0.520174  0.690723  0.207875  0.544086
1    0.931627  0.626650  0.013876  0.673938  0.733962
2     0.04981  0.048008  0.249437  0.831439  0.601342
3    0.797763  0.894796  0.529755  0.704252  0.680406
4    0.011163  0.227519  0.645605  0.258580  0.426857
..        ...       ...       ...       ...       ...
329  0.604284  0.870458  0.643308  0.172701  0.756001
330  0.208461  0.917903  0.915896  0.643644  0.194964
331  0.462388  0.555937  0.916902  0.626838  0.447284
332  0.448996  0.235560  0.620477  0.848534  0.296294
333  0.370733  0.662997  0.179534  0.244978  0.981081

[334 rows x 5 columns]

In [288]:
newdf.loc[0,0] = 26
# helps in accessing the values by specifying the position

In [289]:
newdf

            0         1         2         3         4
0          26  0.520174  0.690723  0.207875  0.544086
1    0.931627  0.626650  0.013876  0.673938  0.733962
2     0.04981  0.048008  0.249437  0.831439  0.601342
3    0.797763  0.894796  0.529755  0.704252  0.680406
4    0.011163  0.227519  0.645605  0.258580  0.426857
..        ...       ...       ...       ...       ...
329  0.604284  0.870458  0.643308  0.172701  0.756001
330  0.208461  0.917903  0.915896  0.643644  0.194964
331  0.462388  0.555937  0.916902  0.626838  0.447284
332  0.448996  0.235560  0.620477  0.848534  0.296294
333  0.370733  0.662997  0.179534  0.244978  0.981081

[334 rows x 5 columns]

In [290]:
newdf.columns = list("ABCDE")

In [291]:
newdf

            A         B         C         D         E
0          26  0.520174  0.690723  0.207875  0.544086
1    0.931627  0.626650  0.013876  0.673938  0.733962
2     0.04981  0.048008  0.249437  0.831439  0.601342
3    0.797763  0.894796  0.529755  0.704252  0.680406
4    0.011163  0.227519  0.645605  0.258580  0.426857
..        ...       ...       ...       ...       ...
329  0.604284  0.870458  0.643308  0.172701  0.756001
330  0.208461  0.917903  0.915896  0.643644  0.194964
331  0.462388  0.555937  0.916902  0.626838  0.447284
332  0.448996  0.235560  0.620477  0.848534  0.296294
333  0.370733  0.662997  0.179534  0.244978  0.981081

[334 rows x 5 columns]

In [292]:
newdf = newdf.drop('A', axis=1)  
# changes column
newdf

            B         C         D         E
0    0.520174  0.690723  0.207875  0.544086
1    0.626650  0.013876  0.673938  0.733962
2    0.048008  0.249437  0.831439  0.601342
3    0.894796  0.529755  0.704252  0.680406
4    0.227519  0.645605  0.258580  0.426857
..        ...       ...       ...       ...
329  0.870458  0.643308  0.172701  0.756001
330  0.917903  0.915896  0.643644  0.194964
331  0.555937  0.916902  0.626838  0.447284
332  0.235560  0.620477  0.848534  0.296294
333  0.662997  0.179534  0.244978  0.981081

[334 rows x 4 columns]

In [293]:
newdf.loc[[1,2], ['C','D']]

          C         D
1  0.013876  0.673938
2  0.249437  0.831439

In [294]:
newdf.head()

          B         C         D         E
0  0.520174  0.690723  0.207875  0.544086
1  0.626650  0.013876  0.673938  0.733962
2  0.048008  0.249437  0.831439  0.601342
3  0.894796  0.529755  0.704252  0.680406
4  0.227519  0.645605  0.258580  0.426857

In [295]:
newdf.loc[[1,2],:]

          B         C         D         E
1  0.626650  0.013876  0.673938  0.733962
2  0.048008  0.249437  0.831439  0.601342

In [296]:
newdf.loc[(newdf['B']<0.3)]

            B         C         D         E
2    0.048008  0.249437  0.831439  0.601342
4    0.227519  0.645605  0.258580  0.426857
5    0.118182  0.612987  0.938580  0.629769
10   0.130191  0.470501  0.361610  0.320346
11   0.073180  0.312880  0.402995  0.999984
..        ...       ...       ...       ...
312  0.129350  0.887113  0.693245  0.385530
319  0.155765  0.845730  0.152939  0.110229
326  0.127671  0.036935  0.290364  0.473569
327  0.171687  0.154270  0.393523  0.609686
332  0.235560  0.620477  0.848534  0.296294

[113 rows x 4 columns]

In [297]:
newdf.loc[(newdf['B']<0.3) & (newdf['C']>0.1)]

            B         C         D         E
2    0.048008  0.249437  0.831439  0.601342
4    0.227519  0.645605  0.258580  0.426857
5    0.118182  0.612987  0.938580  0.629769
10   0.130191  0.470501  0.361610  0.320346
11   0.073180  0.312880  0.402995  0.999984
..        ...       ...       ...       ...
308  0.185394  0.783791  0.813667  0.654033
312  0.129350  0.887113  0.693245  0.385530
319  0.155765  0.845730  0.152939  0.110229
327  0.171687  0.154270  0.393523  0.609686
332  0.235560  0.620477  0.848534  0.296294

[102 rows x 4 columns]

In [298]:
newdf.head(8)

          B         C         D         E
0  0.520174  0.690723  0.207875  0.544086
1  0.626650  0.013876  0.673938  0.733962
2  0.048008  0.249437  0.831439  0.601342
3  0.894796  0.529755  0.704252  0.680406
4  0.227519  0.645605  0.258580  0.426857
5  0.118182  0.612987  0.938580  0.629769
6  0.518590  0.349785  0.439394  0.756540
7  0.651064  0.011323  0.561389  0.403643

In [299]:
newdf.iloc[0,3]
# access the value at 0 row, and skips 3 column -> value(0,E)

np.float64(0.5440856406624633)

In [300]:
newdf.iloc[[1,2], [1,2]]

          C         D
1  0.013876  0.673938
2  0.249437  0.831439

In [301]:
newdf.head(3)

          B         C         D         E
0  0.520174  0.690723  0.207875  0.544086
1  0.626650  0.013876  0.673938  0.733962
2  0.048008  0.249437  0.831439  0.601342

In [302]:
# {newdf = newdf.drop('E', axis=1) \n newdf} ==== {newdf.drop('E', axis=1, inplace = True)}

In [303]:
newdf.drop('E', axis=1, inplace = True)

In [304]:
newdf

            B         C         D
0    0.520174  0.690723  0.207875
1    0.626650  0.013876  0.673938
2    0.048008  0.249437  0.831439
3    0.894796  0.529755  0.704252
4    0.227519  0.645605  0.258580
..        ...       ...       ...
329  0.870458  0.643308  0.172701
330  0.917903  0.915896  0.643644
331  0.555937  0.916902  0.626838
332  0.235560  0.620477  0.848534
333  0.662997  0.179534  0.244978

[334 rows x 3 columns]

In [305]:
newdf.head()

          B         C         D
0  0.520174  0.690723  0.207875
1  0.626650  0.013876  0.673938
2  0.048008  0.249437  0.831439
3  0.894796  0.529755  0.704252
4  0.227519  0.645605  0.258580

In [306]:
newdf.drop(0, axis=0, inplace=True)
newdf

            B         C         D
1    0.626650  0.013876  0.673938
2    0.048008  0.249437  0.831439
3    0.894796  0.529755  0.704252
4    0.227519  0.645605  0.258580
5    0.118182  0.612987  0.938580
..        ...       ...       ...
329  0.870458  0.643308  0.172701
330  0.917903  0.915896  0.643644
331  0.555937  0.916902  0.626838
332  0.235560  0.620477  0.848534
333  0.662997  0.179534  0.244978

[333 rows x 3 columns]

In [307]:
newdf.drop(2, axis=0, inplace=True)
newdf

            B         C         D
1    0.626650  0.013876  0.673938
3    0.894796  0.529755  0.704252
4    0.227519  0.645605  0.258580
5    0.118182  0.612987  0.938580
6    0.518590  0.349785  0.439394
..        ...       ...       ...
329  0.870458  0.643308  0.172701
330  0.917903  0.915896  0.643644
331  0.555937  0.916902  0.626838
332  0.235560  0.620477  0.848534
333  0.662997  0.179534  0.244978

[332 rows x 3 columns]

In [309]:
newdf.head()
# destructive indexing

          B         C         D
1  0.626650  0.013876  0.673938
3  0.894796  0.529755  0.704252
4  0.227519  0.645605  0.258580
5  0.118182  0.612987  0.938580
6  0.518590  0.349785  0.439394

In [310]:
newdf.reset_index()

     index         B         C         D
0        1  0.626650  0.013876  0.673938
1        3  0.894796  0.529755  0.704252
2        4  0.227519  0.645605  0.258580
3        5  0.118182  0.612987  0.938580
4        6  0.518590  0.349785  0.439394
..     ...       ...       ...       ...
327    329  0.870458  0.643308  0.172701
328    330  0.917903  0.915896  0.643644
329    331  0.555937  0.916902  0.626838
330    332  0.235560  0.620477  0.848534
331    333  0.662997  0.179534  0.244978

[332 rows x 4 columns]

In [311]:
newdf.reset_index(drop = True, inplace=True)

In [312]:
newdf

            B         C         D
0    0.626650  0.013876  0.673938
1    0.894796  0.529755  0.704252
2    0.227519  0.645605  0.258580
3    0.118182  0.612987  0.938580
4    0.518590  0.349785  0.439394
..        ...       ...       ...
327  0.870458  0.643308  0.172701
328  0.917903  0.915896  0.643644
329  0.555937  0.916902  0.626838
330  0.235560  0.620477  0.848534
331  0.662997  0.179534  0.244978

[332 rows x 3 columns]